"""Inhoud per college, gemaakt uit de slides van HC 1-5 en IC 1-4 (map 'anki GZC III' in Drive).

Per college:
  kern       : het college in één zin
  kapstok    : [(kop, [punten])] — de structuur van het college op één pagina
  valkuilen  : waar het op het tentamen misgaat
  vragen     : 5 controlevragen (vraag, juist antwoord, [3 foute antwoorden], uitleg)
  cel        : verzamelkaart in de campagne (emoji, naam, feitje)
  kaarten    : nieuwe kaarten voor wat nog ontbrak (voor, achter, prio) — '\n' wordt een regelovergang
  casus      : 'Wie ben ik?'-kaarten (vignet, diagnose, waarom)
  tabellen   : vergelijkingstabellen (zelfde vorm als in extra_inhoud.py)
  schemas    : zelfgetekende figuren; per verborgen vak één kaart (zelfde vorm als in extra_inhoud.py)

Alleen de colleges met slides staan hier; de rest volgt zodra de slides er zijn.
"""

COLLEGES = {
    # ================================================================== HC 1
    'HC1': dict(
        thema='T1', titel='Hematopoëse', docent='dr. Marije Bartels, kinderarts-hematoloog', bron='HC 1 + IC 1',
        kern='Eén stamcel in de beenmergniche maakt via steeds meer toegewijde voorlopers alle bloedcellen. '
             'Signalen van buiten (groeifactoren) en van binnen (transcriptiefactoren) sturen die keuze. '
             'Een stoornis orden je als te weinig, te veel of slechte kwaliteit, en als aangeboren of verworven.',
        kapstok=[
            ('Waar en wanneer', ['Dooierzak → foetale lever (en milt) → beenmerg; bij volwassenen vooral het axiale skelet.',
                                 'De beenmergomgeving (niche) bepaalt of een stamcel slaapt, zich vernieuwt of differentieert.']),
            ('De stamcel', ['Meestal slapend (quiescent); bij stress gaat hij delen (cycling).',
                            'LT-HSC: levenslange zelfvernieuwing. ST-HSC: beperkte zelfvernieuwing, levert de productie op korte termijn.',
                            'Symmetrische deling: twee stamcellen of twee voorlopers. Asymmetrische deling: één stamcel en één voorloper.',
                            'Multipotent en ongedifferentieerd.']),
            ('Sturing', ['Extrinsiek: groeifactoren en cytokines (EPO, TPO, G-CSF, IL-3).',
                         'Intrinsiek: transcriptiefactoren (bv. GATA1, RUNX1).',
                         'Nieuw model: een dynamisch systeem. Voorlopers kunnen nog van lot wisselen, afhankelijk van de prikkels.']),
            ('Drie lijnen', ['Rood: 84% van alle cellen, ±2 miljoen nieuwe per seconde, levensduur 100-120 dagen. Bij stress-erytropoëse is de cel in ±2 dagen klaar in plaats van ±5 dagen, met minder delingen en meer "rommel".',
                             'Wit: myelopoëse (aangeboren afweer: granulocyten, monocyten → macrofagen en DC) en lymfopoëse (B-cellen rijpen in het beenmerg, T-cellen in de thymus).',
                             'Blauw: megakaryopoëse via TPO → plaatjes. Die doen de primaire hemostase, maar spelen ook een rol bij ontsteking en wondgenezing.']),
            ('Vraag en aanbod', ['Een grotere vraag ontstaat door anemie, hypoxie, infectie of sepsis, schimmels, inflammatie, auto-immuniteit, bloeding en wondgenezing.',
                                 'Doorschieten geeft polycytemie, hyperviscositeit, trombose of bloeding, hyperinflammatie, leukemie of lymfoom en fibrose.']),
            ('IC: gestoorde hematopoëse', ['Vier assen: één of meer lijnen · kwalitatief of kwantitatief · te veel of te weinig · aangeboren of verworven.',
                                           'Onderzoek: bloedbeeld + uitstrijk → beenmergaspiraat (cytologie) én biopt (cellulariteit; essentieel voor het complete beeld).',
                                           'Casussen: pancytopenie met een leeg merg (aplastische anemie) · trombopenie bij vader en zoon (RUNX1 → later MDS) · ernstige neutropenie bij een peuter (ELANE).']),
        ],
        valkuilen=['Een aspiraat laat de cellulariteit niet goed zien. Om te beoordelen of het merg "leeg" is, heb je het biopt nodig.',
                   'Erfelijk beenmergfalen (bv. RUNX1) kan zich pas na een second hit als MDS of AML presenteren. Vraag dus altijd naar de familie.',
                   'Denk bij een pancytopenie niet alleen aan aanmaak, maar ook aan afbraak (milt, antistoffen) en verbruik.'],
        vragen=[
            ('Wat onderscheidt een long-term van een short-term hematopoëtische stamcel?',
             'De LT-HSC kan zichzelf levenslang vernieuwen; de ST-HSC maar beperkt',
             ['De LT-HSC deelt continu; de ST-HSC is slapend', 'De LT-HSC circuleert in het bloed; de ST-HSC zit in het beenmerg',
              'De LT-HSC is al toegewijd aan één cellijn'],
             'LT-HSC staan aan de top, slapen meestal en houden de stamcelpool levenslang in stand. ST-HSC leveren de productie op korte termijn.'),
            ('Wat levert een asymmetrische deling van een stamcel op?', 'Eén stamcel en één voorlopercel',
             ['Twee stamcellen', 'Twee voorlopercellen', 'Een stamcel en een rijpe bloedcel'],
             'Zo blijft de pool even groot terwijl er toch aanmaak is. Een symmetrische deling vergroot of verkleint de pool.'),
            ('Een jongen van 11 heeft Hb 3,0, trombocyten 26 en leukocyten 1,2. Er zijn geen blasten en de infectiediagnostiek is negatief. Welk onderzoek laat het best zien of het merg leeg is?',
             'Beenmergbiopt (cellulariteit)', ['Beenmergaspiraat', 'Flowcytometrie van het bloed', 'Reticulocytengetal'],
             'Alleen het biopt laat de architectuur en cellulariteit zien. Hier was het hypoplastisch: (verworven) aplastische anemie.'),
            ('Een meisje van 14 maanden heeft cellulitis, vaak otitis, spruw en een navelstomp die lang niet droog werd. Neutrofielen <0,5 × 10⁹/l. In welk gen verwacht je een mutatie?',
             'ELANE', ['RUNX1', 'JAK2', 'HFE'],
             'Ernstige congenitale neutropenie: ELANE codeert neutrofielen-elastase.'),
            ('Waarom is een familiaire RUNX1-mutatie meer dan alleen een trombopenie?',
             'Het is een erfelijk stamceldefect met een verhoogd risico op MDS en AML na extra mutaties',
             ['Het geeft op termijn altijd ook hemofilie', 'Het gaat vanzelf over na de puberteit', 'Het veroorzaakt ijzerstapeling'],
             'RUNX1 is een transcriptiefactor. Een kiembaanmutatie geeft een kwaliteitsstoornis (dysplasie). Een second en third hit geven dan MDS of AML.'),
        ],
        cel=('🌱', 'Hematopoëtische stamcel', 'Je beenmerg maakt zo\'n 2 miljoen rode bloedcellen per seconde, terwijl de stamcel zelf meestal slaapt.'),
        kaarten=[
            ('Wat is de beenmergniche?',
             'De micro-omgeving in het beenmerg (stromacellen, osteoblasten, endotheel, matrix en signaalstoffen) die de hematopoëtische stamcel huisvest. De niche bepaalt of de stamcel slaapt, zichzelf vernieuwt of differentieert.', False),
            ('Wat betekent het dat de meeste hematopoëtische stamcellen quiescent zijn?',
             'Ze zijn "slapend" (G0) en delen zelden. Dat beschermt tegen uitputting en DNA-schade.\nBij stress (bloeding, infectie, chemotherapie) gaan ze over naar proliferatie (cycling).', False),
            ('Wat is het verschil tussen een long-term en een short-term hematopoëtische stamcel?',
             'LT-HSC: levenslange zelfvernieuwing, meestal slapend, aan de top van de hiërarchie.\nST-HSC: ontstaat uit de LT-HSC, kan zich maar beperkt vernieuwen en levert de productie op korte termijn.', True),
            ('Wat is het verschil tussen een symmetrische en een asymmetrische deling van de stamcel?',
             'Symmetrisch: twee stamcellen (de pool groeit) of twee voorlopers (de pool krimpt).\nAsymmetrisch: één stamcel en één voorloper, zodat de pool gelijk blijft terwijl er toch aanmaak is.', True),
            ('Welke twee soorten signalen sturen de keuze voor een cellijn (lineage commitment)?',
             'Extrinsiek: groeifactoren en cytokines uit de omgeving (EPO, TPO, G-CSF, IL-3).\nIntrinsiek: transcriptiefactoren in de cel (bv. GATA1, RUNX1) die bepalen welke genen aan gaan.\nIn het nieuwe model is dit dynamisch: voorlopers kunnen nog van lot wisselen.', True),
            ('Noem vier feiten over de rode bloedcel uit het hematopoësecollege',
             '84% van alle lichaamscellen is een erytrocyt.\nEr worden circa 2 miljoen nieuwe per seconde gemaakt.\nLevensduur 100-120 dagen.\nGeen kern, DNA of RNA, geen organellen, geen eiwitsynthese.', False),
            ('Wat is het verschil tussen steady-state- en stress-erytropoëse?',
             'Steady state: van pro-erytroblast tot erytrocyt duurt circa 5 dagen, en één pro-erytroblast levert 8 reticulocyten.\nStress (bloeding, hemolyse): circa 2 dagen, met minder celdelingen. Gevolg: grotere cellen met resten van ijzer, ribosomen en Hb (polychromasie, hoger MCV).', True),
            ('Wat zijn de functies van neutrofielen, en wat is de keerzijde?',
             'Fagocytose, degranulatie, productie van zuurstofradicalen (NADPH-oxidase) en NETs (neutrophil extracellular traps).\nKeerzijde: weefselschade en hyperinflammatie, bv. bij ARDS.', False),
            ('Welke functies hebben bloedplaatjes naast de primaire hemostase?',
             'Ontsteking en afweer (ze binden bacteriën en rekruteren leukocyten), wondgenezing en angiogenese (via groeifactoren als PDGF en VEGF).', False),
            ('Wat gebeurt er als de hematopoëse doorschiet?',
             'Rood: polycytemie en hyperviscositeit.\nPlaatjes: trombose én bloeding.\nWit: hyperinflammatie en overgevoeligheid.\nKlonaal: leukemie, lymfoom, fibrose.', False),
            ('Langs welke vier assen beschrijf je een gestoorde hematopoëse?',
             '1) Eén of meer cellijnen (single- of multi-lineage)\n2) Kwalitatief of kwantitatief\n3) Te veel of te weinig\n4) Aangeboren of verworven', True),
            ('Wat is het verschil tussen erfelijk en verworven beenmergfalen?',
             'Erfelijk (IBMFS, bv. Fanconi-anemie, Diamond-Blackfan-anemie): een kiembaandefect, vaak familiair en met andere afwijkingen zoals dysmorfie of groeiproblemen.\nVerworven aplastische anemie: geen aanwijsbare oorzaak (waarschijnlijk immuundysregulatie), meestal een blanco voorgeschiedenis zonder andere symptomen.', True),
            ('Wat hoort bij de anamnese en het lichamelijk onderzoek van een kind met pancytopenie?',
             'Anamnese: voorgeschiedenis incl. groei en ontwikkeling, infecties, tropenbezoek, dieet, medicatie, familie.\nLO: acuut ziek?, bleek of geel, dysmorfieën, lever en milt, lymfeklieren, huid (petechiën, hematomen).', False),
            ('Wat is een familiaire RUNX1-mutatie, en waarom is die belangrijk?',
             'Een erfelijk stamceldefect in een transcriptiefactor, met trombocytopenie en trombopathie; vaak heeft een ouder het ook.\nNa een second en third hit kan het overgaan in MDS of AML: kwaliteitsstoornis → dysplasie → maligniteit.', True),
            ('Wat is ernstige congenitale neutropenie, en welk gen is het bekendst?',
             'Een erfelijke aanmaakstoornis met neutrofielen <0,5 × 10⁹/l vanaf de geboorte: ernstige bacteriële infecties (cellulitis, otitis) en spruw.\nHet bekendste gen is ELANE, dat neutrofielen-elastase codeert.', False),
        ],
        casus=[
            ('Jongen, 11 jaar, blanco voorgeschiedenis. Al weken moe en bleek, houdt voetbal niet meer vol. Hb 3,0, trombocyten 26, leukocyten 1,2. Geen blasten, infectiediagnostiek negatief. Beenmergbiopt hypoplastisch zonder infiltratie.',
             'Verworven aplastische anemie', 'Pancytopenie met een leeg merg zonder infiltratie, zonder aanwijzingen voor erfelijk beenmergfalen. Eerst ondersteunende zorg (transfusies, infectiepreventie).'),
            ('Jongen, 3 jaar, koorts met petechiën, krijgt snel blauwe plekken en heeft soms een bloedneus. Zijn vader heeft ook lage bloedplaatjes. Jaren later dysplasie in het beenmerg.',
             'Familiaire RUNX1-mutatie met overgang naar MDS', 'Een erfelijk stamceldefect (transcriptiefactor) geeft trombopenie en trombopathie. Een second en third hit geven MDS of AML.'),
            ('Meisje, 14 maanden, opgenomen met cellulitis. Vaak otitis, als baby veel luieruitslag en spruw. Neutrofielen <0,5 × 10⁹/l, verder normaal bloedbeeld.',
             'Ernstige congenitale neutropenie (ELANE)', 'Een geïsoleerde, ernstige neutropenie vanaf jonge leeftijd met bacteriële en schimmelinfecties. ELANE codeert neutrofielen-elastase.'),
        ],
        tabellen=[
            dict(id='gestoord', titel='Gestoorde hematopoëse: oorzaken (IC 1)', kolommen=['Oorzaken'], rijen=[
                ('Te weinig door aanmaak', ['Deficiënties, infecties, verdringing, beenmergfalen, genetisch']),
                ('Te weinig door afbraak', ['Hypersplenisme, antistoffen, mechanisch, toxisch']),
                ('Te weinig door verlies of verbruik', ['Bloeden, infectie']),
                ('Te veel aanmaak', ['Infectie, maligniteit, genetisch, toxisch']),
                ('Slechte kwaliteit', ['Beenmergfalen, maligniteit (dysplasie → MDS/AML), genetisch, toxisch']),
            ]),
        ],
        schemas=[
            dict(id='hierarchie', titel='Hiërarchie van de hematopoëse', w=640, h=430, boxes=[
                ('lthsc', 230, 12, 180, 40, 'LT-HSC', 'Langetermijnstamcel: levenslange zelfvernieuwing, meestal slapend in de niche.'),
                ('zelf', 450, 12, 170, 40, 'zelfvernieuwing', None),
                ('sthsc', 215, 78, 210, 40, 'ST-HSC', 'Kortetermijnstamcel: beperkte zelfvernieuwing, levert de productie op korte termijn.'),
                ('cmp', 40, 148, 250, 42, 'Myeloïde voorloper (CMP)', 'Gemeenschappelijke myeloïde voorloper: bron van rode cellen, plaatjes, granulocyten en monocyten.'),
                ('clp', 330, 148, 260, 42, 'Lymfoïde voorloper (CLP)', 'Gemeenschappelijke lymfoïde voorloper: bron van B-, T- en NK-cellen.'),
                ('mep', 10, 222, 165, 42, 'MEP', 'Megakaryocyt-erytroïde voorloper: splitst naar rood (EPO) en plaatjes (TPO).'),
                ('gmp', 190, 222, 165, 42, 'GMP', 'Granulocyt-monocytvoorloper, gestuurd door G-CSF en GM-CSF.'),
                ('ery', 5, 300, 82, 40, 'Erytrocyt', None),
                ('plt', 93, 300, 88, 40, 'Trombocyt', 'Plaatjes ontstaan uit megakaryocyten in het merg, gestuurd door TPO uit de lever. Ze leven 8-10 dagen.'),
                ('gran', 190, 300, 92, 40, 'Granulocyt', None),
                ('mono', 288, 300, 80, 40, 'Monocyt', 'Wordt in het weefsel macrofaag of dendritische cel.'),
                ('mac', 262, 370, 130, 40, 'Macrofaag / DC', None),
                ('b', 392, 300, 70, 40, 'B-cel', None),
                ('t', 470, 300, 70, 40, 'T-cel', 'Ontstaat in het beenmerg en rijpt in de thymus.'),
                ('nk', 548, 300, 80, 40, 'NK-cel', 'Natural killer-cel: lymfoïde cel van de aangeboren afweer.'),
                ('thymus', 470, 370, 70, 36, 'thymus', None),
            ], arrows=[('lthsc', 'sthsc', '->'), ('lthsc', 'zelf', '--'), ('sthsc', 'cmp', '->'), ('sthsc', 'clp', '->'),
                       ('cmp', 'mep', '->'), ('cmp', 'gmp', '->'), ('mep', 'ery', '->'), ('mep', 'plt', '->'),
                       ('gmp', 'gran', '->'), ('gmp', 'mono', '->'), ('mono', 'mac', '->'),
                       ('clp', 'b', '->'), ('clp', 't', '->'), ('clp', 'nk', '->'), ('t', 'thymus', '--')]),
        ],
    ),

    # ================================================================== HC 2
    'HC2': dict(
        thema='T1', titel='Erytropoëse en zuurstofvoorziening', docent='dr. Joline Saes en dr. Eduard van Beers, internist-hematologen',
        bron='HC 2 + IC 2',
        kern='Rode cellen bestaan om zuurstof te vervoeren. De nier meet de zuurstofspanning (HIF) en stuurt bij met EPO. '
             'IJzer is onmisbaar maar giftig: de opname wordt strak geregeld (hepcidine en ferroportine), de uitscheiding helemaal niet. '
             'Vrij ijzer katalyseert de vorming van zuurstofradicalen.',
        kapstok=[
            ('Erytropoëse', ['MEP → pro-erytroblast → erytroblasten → de kern wordt uitgestoten → reticulocyt → erytrocyt. Rijping en ijzeropname duren ±3 weken; de rode cel leeft 120 dagen.',
                             'Bouwstoffen: ijzer, B12, foliumzuur, aminozuren, vetzuren en hormonen. Een tekort geeft anemie.']),
            ('Hemoglobine', ['4 globineketens met elk een heemgroep (ijzer + porfyrine).',
                             'HbA (α2β2) 97-98% · HbA2 (α2δ2) <3% · HbF (α2γ2) <1%, bij de neonaat >70%.']),
            ('Regelkring', ['De O2-sensor zit in de nier (HIF; VHL breekt HIF af als er genoeg O2 is) → EPO → CFU-E.',
                            'De O2-dissociatiecurve verschuift naar rechts door 2,3-DPG, zuur en warmte.',
                            'CaO2 ≈ 1,34 × Hb × SaO2 (+ opgelost O2): Hb is de grootste knop.']),
            ('IJzer', ['Voeding 10-20 mg/dag (Fe³⁺), opname 1-2 mg in het duodenum (Fe²⁺ via DMT1, na reductie door maagzuur en vitamine C). Export via ferroportine.',
                       'Recycling via macrofagen ±25 mg/dag; verlies ±1 mg/dag.',
                       'Hepcidine (lever) blokkeert ferroportine. ↑ bij ontsteking en ijzeroverschot; ↓ bij ijzergebrek, hypoxie en erythroferrone.',
                       'De uitscheiding wordt niet gereguleerd!']),
            ('Opslag en transport', ['Ferritine: 24 subunits, tot 4500 ijzeratomen. Hemosiderine: aggregaten na afbraak van de mantel (Pruisisch blauw).',
                                     'Transferrine: plasmatransport, 2 Fe per molecuul, saturatie normaal 20-30%, bacteriostatisch. Lactoferrine: in secreten, rol in de afweer.']),
            ('Zuurstof en radicalen', ['O2 → H2O kost 4 elektronen. Bij onvolledige reductie ontstaan O2⁻, H2O2 en •OH.',
                                       'Fe²⁺ katalyseert de vorming van radicalen (Fenton/Haber-Weiss).',
                                       'Bronnen: NADPH-oxidase, mitochondriën, P450, xanthine-oxidase (ischemie-reperfusie), toxische stoffen.',
                                       'Oxidatieve stress = een disbalans tussen pro- en antioxidanten, ten gunste van de pro-oxidanten.']),
            ('IC-casussen', ['Chronische ontsteking → anemie bij chronische ziekte.',
                             'Chronische hemolyse → hyperplastisch merg en ijzerstapeling.',
                             'Erytrocytose met een "normaal" EPO → Chuvash (VHL).',
                             'Hemochromatose (HFE C282Y): saturatie ≥45% en hoog ferritine → aderlaten.',
                             'ARDS: neutrofielen + radicalen.']),
        ],
        valkuilen=['Een "normaal" EPO bij een veel te hoog Hb is níet normaal: het had onderdrukt moeten zijn.',
                   'Ferritine is ook een acutefase-eiwit. Een hoog ferritine betekent niet altijd ijzerstapeling: kijk naar de transferrinesaturatie.',
                   'Het lichaam kan ijzer niet actief uitscheiden. Stapeling ontstaat dus sluipend (transfusies, ineffectieve erytropoëse, HFE).'],
        vragen=[
            ('Welk hormoon reguleert de ijzerhuishouding, en hoe?',
             'Hepcidine: het blokkeert ferroportine, waardoor de opname daalt en macrofagen minder ijzer afgeven',
             ['EPO: het verhoogt de ijzeropname via DMT1', 'Transferrine: het zorgt voor uitscheiding via de nier',
              'Ferritine: het stimuleert de afgifte uit de lever'],
             'Hepcidine uit de lever is de "insuline voor ijzer". De uitscheiding wordt niet gereguleerd.'),
            ('Man, 20 jaar: Hb 14,1 mmol/l, Ht 0,66, geen JAK2-mutatie, EPO 14 IU/l (ref. 4-29). Wat is de beste interpretatie?',
             'Het EPO is inadequaat normaal: denk aan een defecte zuurstofsensor (bv. VHL/Chuvash)',
             ['Het EPO is normaal, dus er is niets aan de hand', 'Het lage EPO bewijst polycythaemia vera', 'Het hoge EPO wijst op een EPO-producerende tumor'],
             'Bij zo\'n hoog Hb hoort het EPO onderdrukt te zijn. Homozygote VHL-mutatie: HIF wordt niet afgebroken.'),
            ('Hoe wordt de uitscheiding van ijzer geregeld?', 'Niet: ijzer gaat alleen passief verloren (afschilferende cellen, bloedverlies)',
             ['Via hepcidine in de nier', 'Via de gal, gestuurd door ferritine', 'Via het zweet, gestuurd door EPO'],
             'Daarom gebeurt alle regulatie aan de opnamekant, en stapelt een overschot zich op.'),
            ('In welke situatie is hepcidine juist laag?', 'Bij ineffectieve erytropoëse bij thalassemie (veel erythroferrone)',
             ['Bij actieve reumatoïde artritis (IL-6)', 'Bij ijzerstapeling door veel transfusies', 'Bij een acute infectie'],
             'Erythroferrone uit het actieve merg onderdrukt hepcidine. Daardoor stapelt ijzer zich ook zonder transfusies op.'),
            ('Waarom geeft ischemie-reperfusie weefselschade?',
             'Tijdens de ischemie hoopt hypoxanthine zich op en wordt xanthine-dehydrogenase omgezet in xanthine-oxidase. Bij reperfusie ontstaan dan superoxide en H2O2, en met ijzer hydroxylradicalen',
             ['Door een tekort aan EPO na de ischemie', 'Door de afbraak van hemoglobine tot bilirubine', 'Doordat transferrine verzadigd raakt'],
             'Een klassiek voorbeeld van oxidatieve stress. Fe²⁺ katalyseert de vorming van •OH (Haber-Weiss/Fenton).'),
        ],
        cel=('🔴', 'Reticulocyt', 'Een reticulocyt is een jonge rode cel met nog wat RNA. Bij stress-erytropoëse is hij in ±2 dagen klaar in plaats van ±5 dagen.'),
        kaarten=[
            ('Welke bouwstoffen heeft de erytropoëse nodig?',
             'IJzer (en andere metalen zoals koper), vitamine B12, foliumzuur en andere vitaminen, aminozuren, vetzuren (membraan) en hormonen (EPO, schildklierhormoon, androgenen).\nEen tekort aan één bouwsteen geeft al anemie.', False),
            ('Hoeveel ijzer zit er in de voeding, hoeveel neem je op, en hoeveel wordt er dagelijks gerecycled?',
             'Voeding 10-20 mg/dag, opname 1-2 mg (in het duodenum); dagelijks gaat circa 1 mg verloren.\nVia macrofagen (oude erytrocyten) wordt circa 25 mg/dag gerecycled: de interne kringloop is veel groter dan opname en verlies.', True),
            ('Hoe wordt de uitscheiding van ijzer geregeld?',
             'Niet. Er is geen actief uitscheidingsmechanisme: ijzer gaat alleen passief verloren (afschilferende darm- en huidcellen, bloedverlies).\nAlle regulatie zit dus aan de opnamekant (hepcidine), en een overschot stapelt zich sluipend op.', True),
            ('Waar zit het meeste ijzer in het lichaam, en welke twee organen regelen de ijzerhuishouding?',
             'Vooral in erytrocyten (hemoglobine) en in macrofagen (RES).\nRegulatie: de darm (enterocyt: ijzer doorgeven aan het bloed of met de cel afstoten) en de lever (hepatocyt: maakt hepcidine).', False),
            ('Hoe hoog is de transferrinesaturatie normaal, en wanneer is transferrine "verzadigd"?',
             'Eén transferrinemolecuul bindt maximaal 2 ijzeratomen. Normaal is gemiddeld 20-30% van de bindingsplaatsen bezet.\nEen nuchtere saturatie ≥45% is verdacht voor ijzerstapeling.', True),
            ('Hoe bereken je het arteriële zuurstofgehalte (CaO2), en welke parameter weegt het zwaarst?',
             'CaO2 ≈ 1,34 × Hb × SaO2 + 0,003 × PaO2 (Hb in g/dl, PaO2 in mmHg).\nHet opgeloste deel is verwaarloosbaar: Hb en saturatie bepalen het zuurstofgehalte.\nKlimmers op de Everest hebben een extreem lage PaO2, maar compenseren dat deels met een hoger Hb.', False),
            ('Wat is een vrij radicaal?',
             'Een atoom of molecuul met een ongepaard elektron in de buitenste schil, en daardoor zeer reactief. Voorbeelden: superoxide (O2⁻) en het hydroxylradicaal (•OH).\nWaterstofperoxide is geen radicaal, maar wel een reactieve zuurstofmetaboliet.', False),
            ('Waarom ontstaan er zuurstofradicalen bij de reductie van zuurstof?',
             'Volledige reductie van O2 tot H2O vraagt 4 elektronen. Bij onvolledige reductie ontstaan toxische tussenproducten: superoxide, waterstofperoxide en het hydroxylradicaal.\nZonder katalysator verloopt de reactie zeer langzaam; ijzer (Fe²⁺/Fe³⁺) is zo\'n katalysator.', False),
            ('Welke systemen vormen zuurstofradicalen?',
             'NADPH-oxidase in fagocyten (respiratory burst), mitochondriën (lek uit de ademhalingsketen), cytochroom P450, xanthine/xanthine-oxidase (ischemie-reperfusie), en toxische stoffen: paraquat, bleomycine, adriamycine (doxorubicine), nitrofurantoïne.', False),
            ('Hoe veroorzaakt ischemie-reperfusie weefselschade?',
             'Tijdens de ischemie wordt ATP afgebroken tot hypoxanthine, en zet een Ca²⁺-afhankelijk protease xanthine-dehydrogenase om in xanthine-oxidase.\nBij reperfusie zet xanthine-oxidase hypoxanthine met O2 om: er ontstaan urinezuur, superoxide en H2O2. Met Fe²⁺ (Haber-Weiss/Fenton) wordt dat het hydroxylradicaal → weefselschade.', False),
            ('Wat is oxidatieve stress?',
             'Een disbalans tussen pro-oxidanten en antioxidanten, ten gunste van de pro-oxidanten.\nGevolg: schade aan membranen (lipidenperoxidatie), eiwitten en DNA, en uiteindelijk verlies van orgaanfunctie.', False),
            ('Welke antioxidanten beschermen de cel?',
             'Enzymen: superoxide-dismutase (O2⁻ → H2O2), catalase en glutathionperoxidase (H2O2 → H2O).\nScavengers: glutathion, vitamine C en E, urinezuur.\nDaarnaast vangen ijzerbindende eiwitten (transferrine, ferritine) vrij ijzer weg.', False),
            ('Bij welke ziekten speelt oxidatieve stress een rol in de pathogenese?',
             'IJzerstapeling, chronische ontsteking (reumatoïde artritis), ARDS, atherosclerose, COPD, de ziekte van Alzheimer, hypertensie, diabetes en obesitas.', False),
            ('Hoe ontstaat longschade bij ARDS volgens het erytropoësecollege?',
             'Massale influx van neutrofielen in de long → veel vrije radicalen en te weinig antioxidanten.\nLipidenperoxidatie en endotheeldysfunctie geven een hogere capillaire permeabiliteit (longoedeem), V/Q-mismatch en een hogere pulmonale vaatweerstand, tot multiorgaanfalen toe.', False),
            ('Wat vind je van een EPO van 14 IU/l (ref. 4-29) bij een Hb van 14,1 mmol/l?',
             'Inadequaat normaal: bij zo\'n hoog Hb zou het EPO onderdrukt moeten zijn. Er wordt dus EPO gemaakt alsof er hypoxie is.\nDenk aan een secundaire erytrocytose met een defecte zuurstofsensor (bv. VHL/Chuvash) of aan hemoglobine met een hoge O2-affiniteit.', True),
            ('Bij wie komt HFE-hemochromatose klinisch tot uiting, en wanneer?',
             'Bij C282Y-homozygoten is er klinische expressie bij circa 28% van de mannen tegenover 1% van de vrouwen (menstruatie en zwangerschappen beschermen).\nMeestal tussen het 40e en 60e jaar, bij mannen gemiddeld 10 jaar eerder.', True),
            ('Hoe vaak komt HFE-hemochromatose voor?',
             'Het is de meest voorkomende recessieve ziekte in de westerse wereld: 1 op de 10 Nederlanders is drager, en NL en België tellen samen ruim 70.000 homozygoten.\nDe mutatie ontstond circa 2000 jaar geleden bij Kelten/Vikingen. Bij >90% van de klassieke gevallen (type 1) gaat het om C282Y-homozygotie.', False),
            ('Hoe behandel je hemochromatose, en wie screen je?',
             'Aderlaten (in het begin wekelijks) of erytrocytaferese tot een ferritine rond 50 µg/l, daarna onderhoud. Bijwerkingen: palpitaties, collaps, duizeligheid. Leverwaarden en hartfunctie kunnen herstellen.\nScreen eerstegraads familieleden (saturatie, ferritine, HFE).', True),
        ],
        casus=[
            ('Man, 20 jaar, soms kortademig en duizelig. Hb 14,1 mmol/l, hematocriet 0,66, MCV 91. Geen hemoglobinopathie, geen JAK2-mutatie, EPO 14 IU/l (ref. 4-29).',
             'Congenitale erytrocytose (Chuvash-polycytemie, homozygote VHL-mutatie)', 'Het EPO is inadequaat normaal: de zuurstofsensor meldt ten onrechte hypoxie. Een secundaire, congenitale erytrocytose.'),
            ('Man, 52 jaar, diabetes en impotentie, later een gedilateerde cardiomyopathie en stijgende leverenzymen. Ferritine 3711 µg/l, ijzerverzadiging 88%, testosteron laag.',
             'Hereditaire hemochromatose (homozygoot HFE C282Y)', 'IJzerstapeling in de pancreas (diabetes), hypofyse en testis (hypogonadisme), het hart en de lever. Behandeling: aderlaten of erytrocytaferese.'),
            ('Man, 24 jaar, sinds een dag hoge koorts, hypotensie en tachycardie. Ondanks maximale zuurstof daalt de saturatie naar 80%. X-thorax: diffuse bilaterale verdichtingen.',
             'ARDS bij sepsis', 'Neutrofielen en vrije radicalen beschadigen het alveolocapillaire membraan → permeabiliteitsoedeem. Een voorbeeld van oxidatieve stress.'),
        ],
        tabellen=[
            dict(id='erytrocytose', titel='Oorzaken van erytrocytose (polycytemie)', kolommen=['Congenitaal', 'Verworven'], rijen=[
                ('Primair (EPO laag)', ['EPO-receptormutatie', 'Polycythaemia vera (JAK2)']),
                ('Secundair (via EPO)', ['Defecte O2-sensor (VHL/Chuvash, PHD2, HIF2α), Hb met hoge O2-affiniteit, 2,3-DPG-deficiëntie',
                                         'Centrale hypoxie (long, hart, hoogte, roken), lokale hypoxie (nierarteriestenose), EPO-producerende tumor, medicatie (EPO, testosteron)']),
            ]),
        ],
        schemas=[
            dict(id='ijzerkringloop', titel='De ijzerkringloop', w=640, h=330, boxes=[
                ('darm', 15, 25, 190, 56, 'Darm: opname\n1-2 mg/dag', 'Duodenum: DMT1 neemt Fe²⁺ op, ferroportine exporteert het naar het plasma.'),
                ('plasma', 225, 25, 190, 56, 'Plasma: transferrine', 'Transferrine vervoert ijzer (max. 2 atomen per molecuul; saturatie normaal 20-30%).'),
                ('bm', 435, 25, 190, 56, 'Beenmerg:\nerytropoëse', None),
                ('ery', 435, 140, 190, 56, 'Erytrocyten\n(meeste ijzer)', 'Het grootste deel van het lichaamsijzer zit in hemoglobine.'),
                ('mac', 225, 140, 190, 56, 'Macrofagen (RES):\nrecycling 25 mg/dag', 'Oude erytrocyten worden afgebroken; het ijzer gaat via ferroportine terug naar het plasma.'),
                ('lever', 15, 140, 190, 56, 'Lever: hepcidine\n(+ opslag als ferritine)', 'Hepcidine blokkeert ferroportine in darm en macrofaag. De lever slaat ook ijzer op als ferritine.'),
                ('verlies', 225, 255, 190, 56, 'Verlies ±1 mg/dag\n(niet gereguleerd)', 'Alleen passief verlies: afgeschilferde cellen en bloed. Er is geen actieve uitscheiding.'),
            ], arrows=[('darm', 'plasma', '->'), ('plasma', 'bm', '->'), ('bm', 'ery', '->'), ('ery', 'mac', '->'),
                       ('mac', 'plasma', '->'), ('lever', 'darm', '-|'), ('lever', 'mac', '-|'), ('mac', 'verlies', '--')]),
            dict(id='reperfusie', titel='Ischemie-reperfusieschade', w=640, h=350, boxes=[
                ('isch', 15, 20, 290, 56, 'Ischemie: ATP → AMP\n→ hypoxanthine', 'Zonder zuurstof wordt ATP afgebroken; hypoxanthine hoopt zich op.'),
                ('xo', 335, 20, 290, 56, 'Ca²⁺-protease: xanthine-\ndehydrogenase → -oxidase', 'Calciuminflux activeert een protease dat het enzym omzet in de oxidasevorm, die O2 als elektronacceptor gebruikt.'),
                ('rep', 15, 180, 170, 56, 'Reperfusie:\nO2 komt terug', None),
                ('prod', 215, 180, 250, 56, 'Superoxide (O2⁻) + H2O2\n(+ urinezuur)', 'Xanthine-oxidase zet hypoxanthine en xanthine met O2 om; daarbij ontstaan superoxide en waterstofperoxide.'),
                ('fe', 15, 275, 270, 56, 'Fe²⁺: Haber-Weiss /\nFenton-reactie', 'IJzer katalyseert de omzetting van H2O2 in het uiterst reactieve hydroxylradicaal.'),
                ('oh', 355, 275, 270, 56, '•OH → weefselschade', 'Lipidenperoxidatie en schade aan eiwitten en DNA: reperfusieschade.'),
            ], arrows=[('isch', 'prod', '->'), ('xo', 'prod', '->'), ('rep', 'prod', '->'), ('prod', 'fe', '->'), ('fe', 'oh', '->')]),
        ],
    ),

    # ================================================================== HC 3
    'HC3': dict(
        thema='T1', titel='Anemie', docent='dr. Joline Saes, internist-hematoloog', bron='HC 3 + IC 3',
        kern='Anemie is geen diagnose maar een symptoom. Analyseer haar altijd van twee kanten: kinetisch (aanmaak ↓, afbraak ↑ of verlies, met de reticulocyten als kompas) '
             'en morfologisch (MCV <82, 82-98 of >98 fl). Daarna volgt gericht aanvullend onderzoek.',
        kapstok=[
            ('Definitie', ['Onvoldoende rodecelmassa voor het O2-transport. WHO: Hb <8,1 mmol/l (man) of <7,5 mmol/l (vrouw).',
                           'Het Hb is een concentratie: let op bij dehydratie en bij een acute bloeding (eerst normaal).',
                           'Komt voor bij 14% van de 70-plussers.']),
            ('De erytrocyt', ['Membraan + hemoglobine + enzymen. Energie via anaerobe glycolyse; NADPH via G6PD.',
                              'Afbraak na 110-120 dagen in milt en lever → ongeconjugeerd bilirubine → lever → gal → stercobiline (feces) en urobiline (urine).']),
            ('Lab', ['Ht: M 0,41-0,50, V 0,36-0,47 · MCV 82-98 fl · MCHC 19-23 mmol/l · reticulocyten 25-120 × 10⁹/l · ferritine.']),
            ('Kinetisch', ['Aanmaak ↓ (reticulocyten laag): bouwstenen, beenmerg, hormonen (EPO, TSH, androgenen), chronische ziekte.',
                           'Afbraak ↑ (reticulocyten hoog, LDH ↑, bilirubine ↑, haptoglobine ↓). Intrinsiek: Hb-pathie, membraan, enzym. Extrinsiek: antistoffen (Coombs), mechanisch, infectie, PNH, TMA, hypersplenie.',
                           'Verlies: acuut (reticulocyten ↑) of chronisch occult (ijzergebrek, reticulocyten ↓).']),
            ('Morfologisch', ['Micro (<82): ijzergebrek, ACD, thalassemie, sideroblastair, lood.',
                              'Normo (82-98): acuut bloedverlies, ACD, beenmerg, nier, endocrien.',
                              'Macro (>98): reticulocytose, B12/folaat, MDS, alcohol, lever, hypothyreoïdie, medicatie.',
                              'Sferocytose: MCHC ↑.']),
            ('Hemoglobinopathieën', ['Sikkelcelziekte: kwalitatief (β-keten). α- en β-thalassemie: kwantitatief.',
                                     'Dragerschap is geen ziekte en geeft een overlevingsvoordeel bij malaria; partneronderzoek bij kinderwens. De hielprik spoort sikkelcelziekte op.']),
            ('IC-casussen', ['IJzergebrek (vrouw van 26 versus man van 67!).',
                             'ACD bij RA.',
                             'AIHA (Coombs+, prednison).',
                             'B12-tekort met hemolyseparameters (PPI, metformine).',
                             'HbS/β-thalassemie.',
                             'MDS (oudere, MCV ↑, reticulocyten ↓).',
                             'TTP (trombopenie + MAHA → plasmaferese, caplacizumab).']),
        ],
        valkuilen=['Hemolyseparameters met lage reticulocyten? Denk aan een B12-tekort (intramedullaire hemolyse) of een aplastische crise door parvovirus B19.',
                   'Bij een man of een postmenopauzale vrouw met ijzergebrek: scopie, want het is een GI-maligniteit tot het tegendeel bewezen is.',
                   'Het college hanteert een MCV van 82-98 fl als normaal (niet 80-100).'],
        vragen=[
            ('Vrouw, 55 jaar, moe, bleek-geel, tintelingen in beide benen; gebruikt pantoprazol en metformine. Hb 4,9, MCV 112, reticulocyten 12, LDH 673, haptoglobine <0,1. Wat is het meest waarschijnlijk?',
             'Vitamine B12-deficiëntie (met intramedullaire hemolyse)', ['Auto-immuun hemolytische anemie', 'Myelodysplastisch syndroom', 'IJzergebreksanemie'],
             'Macrocytair, lage reticulocyten en toch hemolyseparameters: ineffectieve erytropoëse. PPI en metformine verminderen de B12-opname; de neuropathie past erbij.'),
            ('Welke combinatie past bij hemolyse?', 'LDH ↑, bilirubine ↑, haptoglobine ↓, reticulocyten ↑',
             ['LDH ↓, haptoglobine ↑, reticulocyten ↓', 'Ferritine ↓, transferrine ↑, reticulocyten ↓', 'MCV ↑, reticulocyten ↓, LDH normaal'],
             'Afbraak (LDH, bilirubine), verbruik van haptoglobine en een reagerend beenmerg (reticulocyten).'),
            ('Bij een normocytaire anemie met een verhoogd MCHC en kogelcellen in de uitstrijk denk je aan:', 'Hereditaire sferocytose',
             ['Bèta-thalassemie minor', 'Vitamine B12-deficiëntie', 'Anemie bij chronische ziekte'],
             'Een verhoogd MCHC is zeldzaam en daardoor typisch voor sferocytose (membraandefect, osmotische fragiliteit).'),
            ('Vrouw, 27 jaar: buikpijn, verwardheid, blauwe plekken. Hb 3,4, trombocyten 7, reticulocyten 250, LDH 3200, fragmentocyten. Wat is de eerste behandeling?',
             'Plasmaferese, met caplacizumab en prednison', ['Trombocytentransfusie', 'Splenectomie', 'Intraveneus ijzer'],
             'TTP: auto-antistoffen tegen ADAMTS13. Een spoedsituatie.'),
            ('Waarom zijn leeftijd en geslacht zo belangrijk bij een microcytaire anemie met een laag ferritine?',
             'Bij een man of een postmenopauzale vrouw moet je een gastro-intestinale bloeding of maligniteit uitsluiten (scopie)',
             ['Omdat mannen meer ijzer opnemen dan vrouwen', 'Omdat thalassemie alleen bij vrouwen voorkomt', 'Omdat ferritine bij ouderen onbetrouwbaar is'],
             'Bij een vrouw van 26 is menstrueel bloedverlies de meest waarschijnlijke oorzaak; bij een man van 67 is het occult GI-bloedverlies.'),
        ],
        cel=('🌙', 'Sikkelcel', 'Dragerschap van HbS beschermt tegen ernstige malaria. Daarom komt het vooral voor waar malaria heerste.'),
        kaarten=[
            ('Wat zijn de normaalwaarden van hematocriet, MCV, MCHC en reticulocyten (anemiecollege)?',
             'Ht: man 0,41-0,50, vrouw 0,36-0,47\nMCV: 82-98 fl (= Ht / aantal erytrocyten)\nMCHC: 19-23 mmol/l\nReticulocyten: 25-120 × 10⁹/l', True),
            ('Waarom is het Hb een concentratie, en wanneer misleidt dat?',
             'Hb = de totale hoeveelheid Hb gedeeld door het plasmavolume.\nBij dehydratie is het te hoog. Bij een acute bloeding daalt het pas na hemodilutie (uren). In de zwangerschap (hypervolemie) is het door verdunning lager.', True),
            ('Hoe wekt de erytrocyt energie op, en waarom is dat relevant?',
             'Via anaerobe glycolyse (er zijn geen mitochondriën), plus de hexosemonofosfaatroute voor NADPH (G6PD).\nDefecten in deze enzymen (pyruvaatkinase, hexokinase, G6PD) geven hemolyse.', False),
            ('Waarom zit hemoglobine verpakt in erytrocyten en niet vrij in het plasma?',
             'Vrij plasma-Hb is toxisch (oxidatief, bindt NO, beschadigt de nier) en osmotisch actief; verpakt Hb is veel efficiënter.\nDaarom is intravasculaire hemolyse (vrij Hb) gevaarlijker dan extravasculaire.', False),
            ('Welke hormoontekorten kunnen een anemie geven?',
             'EPO (nierziekte), schildklierhormoon (hypothyreoïdie) en androgenen (hypogonadisme).\nZe geven een hypoproliferatieve, meestal normocytaire anemie met lage reticulocyten.', True),
            ('Wat zijn de extrinsieke oorzaken van hemolyse?',
             'Antistoffen (auto- en allo-immuun; Coombs positief), mechanisch (kunstklep, marshemoglobinurie), infecties (malaria), PNH, micro-angiopathie (TTP, HUS, DIS) en hypersplenie.', True),
            ('Wat is marshemoglobinurie?',
             'Mechanische, intravasculaire hemolyse door herhaalde impact van de voeten op een harde ondergrond (lange marsen, hardlopen). Gevolg: voorbijgaand donkere urine (hemoglobinurie).', False),
            ('Welk type antistof geeft extravasculaire hemolyse, en welk intravasculaire?',
             'IgG (warme antistoffen): extravasculair; de cellen worden in de milt opgeruimd.\nIgM met complementactivatie (koude antistoffen): intravasculair.\nDe directe Coombs-test (DAT) toont IgG en/of complement op de erytrocyt aan.', True),
            ('Wat is het verschil tussen auto- en allo-immuunhemolyse?',
             'Auto: antistoffen tegen de eigen erytrocyten (AIHA).\nAllo: antistoffen tegen vreemde erytrocyten, ontstaan na een eerdere bloedtransfusie of zwangerschap (bv. een transfusiereactie, of hemolytische ziekte van de pasgeborene).', False),
            ('Hoe behandel je een warme auto-immuun hemolytische anemie?',
             'Prednison als eerste lijn; bij onvoldoende effect rituximab (anti-CD20). Daarnaast foliumzuur en zo nodig een transfusie.\nZoek en behandel een onderliggende oorzaak (bv. CLL, lymfoom, auto-immuunziekte, medicatie).', False),
            ('Wat is hemoglobin switching, en waarom is dat klinisch belangrijk?',
             'De overgang van foetaal Hb (HbF, α2γ2) naar volwassen Hb (HbA, α2β2) rond de geboorte; in de eerste levensmaanden daalt HbF tot <1%.\nDaarom presenteren ziekten van de bètaketen (sikkelcelziekte, bèta-thalassemie major) zich pas na circa 6 maanden.', True),
            ('Wat zijn de kenmerken van dragerschap van een hemoglobinopathie?',
             'Geen ziekte, wel een overlevingsvoordeel bij malaria.\nHbS-drager: meestal een normaal bloedbeeld. Thalassemiedrager: vaak een milde microcytaire anemie zónder ijzergebrek.\nBelangrijk voor partneronderzoek bij kinderwens; veel dragers weten het niet.', True),
            ('Wanneer doe je dragerschapsonderzoek naar een hemoglobinopathie?',
             'Bij kinderwens of zwangerschap als (een van) de ouders uit een gebied met een hoge dragerschapsfrequentie komt.\nBij een hemoglobinopathie bij eerste- of tweedegraads familie.\nBij de ouders en familie van een kind met een afwijkende hielprik.\nBij een aanhoudende anemie ondanks ijzersuppletie.', False),
            ('Hoe worden sikkelcelziekte en HbS-dragerschap in Nederland tegenwoordig opgespoord?',
             'Via de hielprik (neonatale screening). Sikkelcelziekte wordt opgespoord en HbS-dragerschap wordt als nevenbevinding gemeld.', False),
            ('Welke membraanafwijkingen van de erytrocyt ken je, en hoe stel je ze vast?',
             'Sferocytose (de meest voorkomende), elliptocytose en stomatocytose.\nDiagnostiek: de morfologie in de uitstrijk en de osmotische resistentie (kogelcellen lyseren sneller).', False),
            ('Welke enzymdefecten van de erytrocyt geven hemolyse?',
             'G6PD-deficiëntie (het meest voorkomend; oxidatieve hemolyse), pyruvaatkinasedeficiëntie en hexokinasedeficiëntie (beide in de glycolyse).', False),
            ('Wat zie je in de uitstrijk bij micro-angiopathische hemolyse?',
             'Fragmentocyten (schistocyten): stukjes erytrocyt die in de microcirculatie aan fibrinedraden kapot zijn geknipt. Vaak samen met trombocytopenie; de hemolyse is intravasculair.\nDenk aan TTP, HUS en DIS.', True),
            ('Wat zijn de oorzaken van trombotische micro-angiopathie (TMA)?',
             'Klassieke TTP (auto-antistoffen tegen ADAMTS13), HUS door Shiga-toxine producerende E. coli (STEC), medicatie (chemotherapie, ciclosporine), maligniteit (DIS), zwangerschap (HELLP), infectie (sepsis, DIS) en maligne hypertensie.', True),
            ('Hoe behandel je TTP?',
             'Spoed: plasmaferese (verwijdert de antistoffen en vult ADAMTS13 aan), caplacizumab (een nanobody tegen VWF dat de plaatjesbinding blokkeert) en prednison (immunosuppressie).', True),
            ('Welke vijf factoren zijn nodig voor een adequate opname van vitamine B12, en wat kan er per factor misgaan?',
             '1) Voldoende inname — veganisme\n2) Maagzuur en pepsine om cobalamine vrij te maken — atrofische gastritis, bariatrische chirurgie, langdurig PPI-gebruik\n3) Pancreasenzymen — pancreasinsufficiëntie, pancreatitis\n4) Intrinsic factor — pernicieuze anemie, maagresectie\n5) Een functionerend ileum — ileumresectie, de ziekte van Crohn', True),
            ('Waarom ontstaat een vitamine B12-deficiëntie langzaam?',
             'De lever heeft een grote voorraad, genoeg voor enkele jaren. Een tekort ontstaat dus pas lang nadat de malabsorptie is begonnen.', False),
            ('Welke medicijnen kunnen een vitamine B12-deficiëntie geven?',
             'Metformine (verminderde opname in het ileum) en langdurig gebruik van protonpompremmers (minder maagzuur, dus minder B12 dat uit de voeding vrijkomt).', True),
            ('Waarom kan een vitamine B12-deficiëntie hemolyseparameters geven?',
             'Door ineffectieve erytropoëse: megaloblastaire voorlopers gaan al in het beenmerg te gronde (intramedullaire hemolyse).\nDaardoor zijn LDH (vaak zeer hoog) en bilirubine verhoogd en is haptoglobine verlaagd, maar de reticulocyten zijn laag.', True),
            ('Wat doet parvovirus B19, en waarom is het gevaarlijk bij chronische hemolyse?',
             'Parvovirus B19 infecteert erytroïde voorlopers en stopt de erytropoëse tijdelijk (reticulocyten ±0).\nBij gezonde mensen is dat onschuldig. Bij een verkorte overleving van de erytrocyten (sikkelcelziekte, sferocytose) geeft het een acute aplastische crise met een diepe anemie.', True),
            ('Hoe interpreteer je deze Hb-elektroforese: HbA 12%, HbA2 4,3%, HbF 19,2% en een extra piek van 64% (HbS), bij een microcytaire hemolytische anemie met pijnaanvallen?',
             'HbS/bèta⁺-thalassemie, een vorm van sikkelcelziekte. HbS overheerst; er is nog wat HbA (dus β⁺ en niet β⁰), en HbA2 en HbF zijn verhoogd.\nDe pijnaanvallen zijn vaso-occlusieve crises.', False),
            ('Wat wil je weten bij een normocytaire anemie bij een patiënt met reumatoïde artritis?',
             'De activiteit van de RA (BSE, CRP).\nDe medicatie: methotrexaat (beenmergsuppressie, macrocytose) en NSAID\'s (gastro-intestinaal bloedverlies).\nDe ijzerstatus, om ACD van (bijkomend) ijzergebrek te onderscheiden.\nBehandeling: de ontsteking onder controle krijgen.', False),
            ('Welke vijf vragen stel je jezelf bij de initiële aanpak van een anemie?',
             '1) Is er een bloeding (acuut of chronisch)?\n2) Is er beenmergsuppressie (volledig bloedbeeld, morfologie)?\n3) Is er hemolyse (reticulocyten, bilirubine, LDH, haptoglobine)?\n4) Is er ijzergebrek, en waarom?\n5) Is er een tekort aan B12 of foliumzuur, en waarom?', True),
            ('Wat hoort er bij de anamnese en het lichamelijk onderzoek van een patiënt met anemie?',
             'Anamnese: leeftijd, geslacht, afkomst, familie, eerdere ziektes en operaties, medicatie, eerdere transfusies.\nLO: lymfeklieren, lever- en miltgrootte, botafwijkingen (en icterus, glossitis, neuropathie).\nDaarna een perifere uitstrijk en gericht lab, zo nodig een Coombs-test.', False),
            ('Welke aangeboren aanmaakstoornissen van de erytrocyt geven een hoog MCV?',
             'Diamond-Blackfan-anemie (pure red cell aplasie), Fanconi-anemie (beenmergfalen) en congenitale dyserytropoëtische anemie.', False),
        ],
        casus=[
            ('Vrouw, 55 jaar, moe, bleek-geel, donkere urine en tintelingen in beide benen. Gebruikt pantoprazol en metformine. Hb 4,9, MCV 112, reticulocyten 12, LDH 673, haptoglobine <0,1.',
             'Vitamine B12-deficiëntie met intramedullaire hemolyse', 'Macrocytair, lage reticulocyten, hemolyseparameters (ineffectieve erytropoëse) en neuropathie. PPI en metformine verminderen de opname.'),
            ('Vrouw, 25 jaar, had drie keer onbegrepen pijn in de schouders die na enkele dagen overging. Hb 6,7, MCV 73, reticulocyten 264, LDH 586, haptoglobine <0,1. Hb-elektroforese: HbS 64%, HbF 19%, HbA2 4,3%, HbA 12%.',
             'HbS/bèta⁺-thalassemie (sikkelcelziekte)', 'Hemolyse met microcytose; HbS overheerst en er is nog wat HbA (β⁺). De pijnaanvallen zijn vaso-occlusieve crises.'),
            ('Hardloper, 30 jaar, heeft na een marathon voorbijgaand roodbruine urine. Verder gezond; haptoglobine licht verlaagd, geen fragmentocyten, DAT negatief.',
             'Marshemoglobinurie', 'Mechanische intravasculaire hemolyse door de herhaalde impact van de voeten. Onschuldig en voorbijgaand.'),
            ('Meisje, 7 jaar, bekend met hereditaire sferocytose. Na een week koorts en een uitslag met rode "geslagen" wangen is ze plots doodsbleek. Hb 3,2, reticulocyten vrijwel 0.',
             'Aplastische crise door parvovirus B19', 'B19 stopt de erytropoëse tijdelijk. Bij een verkorte overleving van de erytrocyten daalt het Hb dan snel. Behandeling: transfusie.'),
        ],
        tabellen=[
            dict(id='mcvmchc', titel='MCV en MCHC bij anemie (HC 3)', kolommen=['MCV / MCHC', 'Oorzaken'], rijen=[
                ('Microcytair, hypochroom', ['↓ / ↓', 'IJzergebrek (ferritine laag), thalassemie']),
                ('Normocytair, normochroom', ['= / =', 'Chronische ziekte, aplastische anemie, hemolyse']),
                ('Normocytair, hyperchroom', ['= of ↓ / ↑', 'Sferocytose']),
                ('Macrocytair', ['↑ / = of ↓', 'Megaloblastair (B12/folaat), MDS, hemolyse met veel reticulocyten']),
            ]),
        ],
        schemas=[
            dict(id='bilirubine', titel='Afbraak van de erytrocyt: van hemoglobine tot bilirubine', w=640, h=430, boxes=[
                ('mac', 15, 15, 270, 56, 'Macrofaag (milt, lever)\nbreekt oude erytrocyten af', 'Na 110-120 dagen: globine → aminozuren, ijzer → hergebruik, heem → biliverdine → bilirubine.'),
                ('unc', 15, 110, 270, 56, 'Ongeconjugeerd bilirubine\n(gebonden aan albumine)', 'Niet wateroplosbaar, dus gebonden aan albumine; komt niet in de urine. Stijgt bij hemolyse.'),
                ('lever', 15, 205, 270, 56, 'Lever: conjugatie\n(glucuronyltransferase)', 'De hepatocyt koppelt bilirubine aan glucuronzuur: wateroplosbaar, geconjugeerd bilirubine.'),
                ('gal', 15, 300, 270, 44, 'Geconjugeerd bilirubine → gal', None),
                ('darm', 355, 300, 270, 56, 'Darm: bacteriën maken\nurobilinogeen', 'Darmbacteriën zetten bilirubine om in urobilinogeen.'),
                ('sterco', 355, 375, 270, 44, 'Feces: stercobiline (bruin)', 'Het grootste deel verlaat het lichaam als stercobiline: de bruine kleur van de ontlasting.'),
                ('poort', 355, 205, 270, 56, 'Poortader: een deel wordt\nteruggeresorbeerd', None),
                ('urine', 355, 110, 270, 56, 'Nier: urobiline in de urine', 'Een klein deel urobilinogeen bereikt via de circulatie de nier. Bij hemolyse is het urine-urobilinogeen verhoogd.'),
            ], arrows=[('mac', 'unc', '->'), ('unc', 'lever', '->'), ('lever', 'gal', '->'), ('gal', 'darm', '->'), ('darm', 'sterco', '->'),
                       ('darm', 'poort', '->'), ('poort', 'urine', '->'), ('poort', 'lever', '--')]),
        ],
    ),

    # ================================================================== HC 4
    'HC4': dict(
        thema='T1', titel='Stolling', docent='prof. dr. Roger Schutgens, internist-hematoloog (Van Creveldkliniek)', bron='HC 4 + IC 4',
        kern='Stolling is een samenspel van vaatwand, bloedplaatjes (primaire hemostase) en stollingsfactoren (secundaire hemostase), in balans met natuurlijke remmers. '
             'Klinisch begin je met de vragen: bloeder of stoller, primair of secundair? Pas daarna komt het lab, en geen enkele routinetest meet het tromboserisico.',
        kapstok=[
            ('Primaire hemostase', ['Vasoconstrictie + plaatjesplug: adhesie (VWF–GPIb), activatie (ADP–P2Y12, TxA2 via COX-1), aggregatie (GPIIb/IIIa + fibrinogeen).',
                                    'Remmers: aspirine/NSAID (COX-1), clopidogrel (P2Y12), abciximab (GPIIb/IIIa).']),
            ('Secundaire hemostase', ['Pro-enzym → enzym, met een cofactor (amplificatie): TF-VIIa → Xa (+ Va) → trombine (IIa) → fibrine; versterking via IXa/VIIIa en XIa.',
                                      'Natuurlijke remmers: antitrombine, proteïne C/S (via trombomoduline), TFPI.']),
            ('Bloedingsneiging', ['Anamnese met de ISTH-BAT-score.',
                                  'Slijmvliezen en direct nabloeden → primair. Gewrichten, spieren en uitgesteld nabloeden → secundair.']),
            ('Testen', ['PFA: alleen om VWD uit te sluiten · PT (extrinsiek + gemeenschappelijk) · aPTT (intrinsiek) · TT (heparine?) · factorbepalingen · LTA.',
                        'Geen enkele routinetest meet het tromboserisico.']),
            ('Antistolling', ['VKA (II, VII, IX, X) · heparine (via AT: Xa + IIa) · fondaparinux (via AT: Xa) · bivalirudine en dabigatran (IIa) · rivaroxaban, apixaban, edoxaban (Xa).']),
            ('Hemofilie', ['1:5000 mannen, NL ±1600 patiënten, 85% A / 15% B, X-gebonden, ⅓ spontane mutatie (Victoria → tsarevitsj Aleksej).',
                           'Ernstig: gewrichts- en spierbloedingen → kraakbeenschade.',
                           'Behandeling: van on demand naar profylaxe (FVIII-halfwaardetijd ±10 uur, dalspiegel >1%) en thuisbehandeling. In de jaren 80 virusbesmetting (HCV, hiv).',
                           'Nieuw: emicizumab, rebalancing (fitusiran, anti-TFPI) en gentherapie.']),
            ('IC-casussen', ['De tabel bloeder of stoller × primair of secundair.',
                             'Kind met nabloeding na adenotomie → primair (VWD of trombopathie).',
                             'Lichte hemofilie A (FVIII 13%).',
                             'VWD (vrouw met menorragie, moeder ook).',
                             'DVT na een operatie (Virchow).',
                             'DIS op de IC (PT en aPTT ↑, plaatjes ↓, fibrinogeen ↓, D-dimeer ↑↑).']),
        ],
        valkuilen=['Een normale PT en aPTT sluiten een bloedingsziekte niet uit (VWD, plaatjesfunctie, FXIII, vaatwand).',
                   'Een negatieve familieanamnese sluit hemofilie niet uit: ⅓ is een spontane mutatie.',
                   'De bloedingstijd is obsoleet; de PFA dient alleen om VWD uit te sluiten.'],
        vragen=[
            ('Man, 18 jaar: pijnlijke dikke knie na licht trauma; zijn oom had "een bloedziekte". PT 14 s (12-15), aPTT 52 s (34-40), FVIII 13%. Wat is de diagnose?',
             'Lichte hemofilie A', ['Ernstige hemofilie A', 'Ziekte van Von Willebrand type 3', 'Vitamine K-deficiëntie'],
             'aPTT verlengd en PT normaal; FVIII van 5-40% = licht. X-gebonden: de oom via de moeder.'),
            ('Hoe werkt emicizumab?', 'Het is een bispecifiek antilichaam dat FIXa en FX aan elkaar koppelt en zo FVIIIa nabootst',
             ['Het verlaagt de aanmaak van antitrombine via RNA-interferentie', 'Het is een gezuiverd FVIII-concentraat met een langere halfwaardetijd', 'Het blokkeert TFPI'],
             'Subcutaan, werkt ook bij remmers, alleen bij hemofilie A. Fitusiran (siRNA tegen antitrombine) en anti-TFPI zijn rebalancers.'),
            ('Welke routinetest voorspelt het tromboserisico?', 'Geen: PT, aPTT, PFA en bloedingstijd zeggen niets over trombose',
             ['De aPTT', 'De PT/INR', 'De PFA'],
             'Deze testen meten alleen (een deel van) de bloedingsneiging.'),
            ('Een IC-patiënt bloedt uit de insteekopeningen. PT +8 s, aPTT +18 s, trombocyten 75, fibrinogeen 0,9 g/l, D-dimeer +++. Wat is er aan de hand?',
             'Diffuse intravasale stolling (DIS)', ['Hemofilie A', 'Immuun-trombocytopenie (ITP)', 'Een overdosis heparine'],
             'Een verbruikscoagulopathie: factoren, plaatjes en fibrinogeen raken op, en de fibrinolyse geeft veel D-dimeer.'),
            ('Waarvoor is de PFA volgens het college eigenlijk alleen bruikbaar?', 'Om de ziekte van Von Willebrand uit te sluiten',
             ['Om hemofilie aan te tonen', 'Om het gebruik van DOAC\'s te controleren', 'Om trombose te voorspellen'],
             'De PFA is een globale, weinig specifieke test van de primaire hemostase.'),
        ],
        cel=('🩹', 'Bloedplaatje', 'Plaatjes hebben geen kern en leven 8-10 dagen. Aspirine remt hun COX-1 onomkeerbaar, dus het effect duurt tot de plaatjes vervangen zijn.'),
        kaarten=[
            ('Wat is het principe van een stollingsreactie?',
             'Een inactief pro-enzym wordt door een actief enzym omgezet in een actief enzym, met een cofactor, op een fosfolipidenoppervlak en met Ca²⁺.\nElke stap versterkt de vorige (amplificatie) en wordt geremd door natuurlijke remmers (regulatie).', False),
            ('Wat is de ISTH-BAT?',
             'Een gestandaardiseerde bloedingsanamnese (bleeding assessment tool). Elke lokalisatie krijgt een score: o.a. neusbloedingen, blauwe plekken, kleine wondjes, mond, maag-darm, hematurie, tandextractie, operatie, menstruatie, postpartum, spieren, gewrichten, CZS.\nAfwijkend: ≥4 bij mannen, ≥6 bij vrouwen, ≥3 bij kinderen.', True),
            ('Welke stollingstest meet welk deel van de hemostase?',
             'PFA: de primaire hemostase (alleen bruikbaar om VWD uit te sluiten).\nPT en aPTT: de secundaire hemostase.\nBloedingstijd: obsoleet.\nGeen van deze testen meet het tromboserisico.', True),
            ('Welke routinestollingstest zegt iets over het tromboserisico?',
             'Geen enkele. PT, aPTT, PFA en bloedingstijd meten alleen de bloedingsneiging.', True),
            ('Waar grijpen fondaparinux (pentasaccharide) en bivalirudine aan?',
             'Fondaparinux: remt factor Xa indirect, via antitrombine.\nBivalirudine: een directe trombineremmer (IIa), intraveneus.', False),
            ('Welke DOAC\'s remmen factor Xa, en welke trombine?',
             'Xa-remmers: rivaroxaban, apixaban, edoxaban (en betrixaban), de "-xabans".\nTrombineremmer: dabigatran (antidotum idarucizumab).', True),
            ('Hoe vaak komt hemofilie voor?',
             'Circa 1 op de 5000 mannen; in Nederland ongeveer 1600 patiënten. 85% heeft hemofilie A, 15% hemofilie B.', False),
            ('Waarom heet hemofilie "the royal disease"?',
             'Koningin Victoria was draagster. Via haar dochters kwam de mutatie in Europese koningshuizen terecht, onder meer bij tsarevitsj Aleksej van Rusland.\nBij Victoria ging het waarschijnlijk om een spontane mutatie, zoals bij 1 op de 3 patiënten.', False),
            ('Welke soorten bloedingen zie je bij ernstige hemofilie?',
             'Spontane bloedingen, bloedingen na overbelasting, en traumatische en iatrogene bloedingen; vooral in gewrichten en spieren.\nHerhaalde gewrichtsbloedingen geven kraakbeenschade (hemofiele artropathie).', False),
            ('Wat is het verschil tussen on-demand en profylactische behandeling van hemofilie?',
             'On demand: stollingsfactor geven zodra er een bloeding is.\nProfylaxe: meerdere keren per week intraveneus factor geven om bloedingen te voorkomen. De dalspiegel blijft dan boven 1-3%, zodat een ernstige hemofilie zich gedraagt als een matige. Minder bloedingen, betere gewrichtsfunctie.', True),
            ('Waarom moet FVIII bij profylaxe zo vaak worden gegeven?',
             'FVIII heeft een halfwaardetijd van circa 10 uur en kan alleen intraveneus. Daarom meerdere keren per week; patiënten leren zichzelf te prikken (thuisbehandeling).', False),
            ('Welke complicatie trof veel hemofiliepatiënten in de jaren 70 en 80?',
             'Virale besmetting via plasmaproducten: hepatitis A, B en C (98% van de patiënten van de Van Creveldkliniek heeft HCV-antistoffen) en hiv (in 1981-1983 raakte volgens het college circa 90% van de behandelde patiënten besmet).', False),
            ('Hoe werkt emicizumab?',
             'Een bispecifiek antilichaam dat factor IXa en factor X tegelijk bindt, en zo de brugfunctie van FVIIIa nabootst.\nSubcutaan, eens per 1-4 weken. Werkt ook bij remmers (inhibitors), maar alleen bij hemofilie A.', True),
            ('Wat is het principe van rebalancingtherapie bij hemofilie?',
             'In plaats van de ontbrekende factor aan te vullen, rem je de natuurlijke antistolling: fitusiran (siRNA dat de aanmaak van antitrombine verlaagt) of antistoffen tegen TFPI (concizumab, marstacimab).\nZo komt de balans weer in evenwicht, bij hemofilie A én B.', False),
            ('Waarom is hemofilie bij uitstek geschikt voor gentherapie?',
             'Het gaat om één gen (F8 of F9), en een kleine stijging van de factorspiegel (al enkele procenten) geeft al veel klinische winst.\nGentherapie met een AAV-vector is door FDA en EMA goedgekeurd.', False),
            ('Welke vier vragen stel je bij een stollingsprobleem (IC stolling)?',
             '1) Word ik gevraagd voor een labafwijking of voor een patiënt?\n2) Is het een bloeder of een stoller?\n3) Is aanvullende diagnostiek nodig?\n4) Is er een optie voor interventie?', False),
            ('Wat is lichttransmissie-aggregometrie (LTA), en welke patronen ken je?',
             'Een plaatjesfunctietest: plaatjesrijk plasma wordt gestimuleerd met agonisten (ADP, collageen, arachidonzuur, epinefrine, TRAP, ristocetine), en de aggregatie wordt gemeten als lichtdoorlating.\nGeen aggregatie behalve met ristocetine = Glanzmann. Alleen ristocetine afwijkend = Bernard-Soulier of VWD. Arachidonzuur afwijkend = aspirine.', False),
            ('Wat is je DD bij een kind met veel blauwe plekken, frequente neusbloedingen en een re-operatie na een adenotomie wegens nabloeding?',
             'Een stoornis in de primaire hemostase: trombocytopenie of trombopathie, of de ziekte van Von Willebrand.\nBij een jongen overweeg je ook (lichte) hemofilie; bij een meisje is dat veel minder waarschijnlijk.', True),
        ],
        casus=[
            ('Man, 18 jaar, pijnlijke gezwollen knie na licht trauma bij voetbal. Krijgt vaker blauwe plekken; zijn oom had "een bloedziekte". PT 14 s (12-15), aPTT 52 s (34-40), FVIII 13%.',
             'Lichte hemofilie A', 'Verlengde aPTT bij een normale PT. Een FVIII van 5-40% = licht. X-gebonden (de oom via de moeder). Rond ingrepen: desmopressine en tranexaminezuur of FVIII.'),
            ('Man, 68 jaar, 5 dagen na een heupoperatie: gezwollen, pijnlijke kuit.',
             'Diepe veneuze trombose', 'Trias van Virchow: stase (immobilisatie), vaatwandschade (de operatie) en hypercoagulabiliteit (postoperatief). Behandeling: antistolling (DOAC of LMWH).'),
            ('IC-patiënt met sepsis bloedt uit alle insteekopeningen. PT +8 s, aPTT +18 s, trombocyten 75, fibrinogeen 0,9 g/l, D-dimeer sterk verhoogd.',
             'Diffuse intravasale stolling (DIS)', 'Gegeneraliseerde activatie van de stolling: verbruik van factoren (PT en aPTT ↑), plaatjes en fibrinogeen, met veel fibrineafbraak (D-dimeer). Behandel de oorzaak.'),
        ],
        tabellen=[
            dict(id='bloederstoller', titel='Bloeder of stoller? (IC 4)', kolommen=['Bloeding', 'Trombose', 'Diagnostiek bij bloeding', 'Diagnostiek bij trombose'], rijen=[
                ('Primair (plaatjes, VWF)', ['Trombopenie/-pathie, ziekte van Von Willebrand', 'Trombocytose, TTP', 'Bloedbeeld, plaatjesfunctie, VWF', 'Bloedbeeld, ADAMTS13']),
                ('Secundair (stollingsfactoren)', ['Tekort aan een stollingsfactor', 'Trombofilie', 'PT, aPTT, TT, stollingsfactoren', 'Specifieke (trombofilie)testen']),
            ]),
        ],
        schemas=[
            dict(id='antistolling', titel='Waar grijpen de antistollingsmiddelen aan?', w=640, h=380, boxes=[
                ('tf', 20, 20, 170, 44, 'TF-VIIa', None),
                ('ix', 450, 20, 170, 44, 'IXa + VIIIa', None),
                ('xa', 235, 105, 170, 48, 'Xa (+ Va)', None),
                ('iia', 235, 215, 170, 48, 'Trombine (IIa)', None),
                ('fib', 215, 315, 210, 44, 'Fibrinogeen → fibrine', None),
                ('xaban', 450, 90, 175, 56, 'Rivaroxaban, apixaban,\nedoxaban', 'Directe orale Xa-remmers (DOAC\'s). Antidotum: andexanet alfa of protrombinecomplex.'),
                ('fonda', 450, 160, 175, 40, 'Fondaparinux', 'Pentasaccharide: remt Xa indirect via antitrombine.'),
                ('hep', 15, 140, 175, 56, 'Heparine\n(via antitrombine)', 'Versterkt antitrombine: remt trombine én Xa (LMWH vooral Xa). Antidotum: protaminesulfaat.'),
                ('dabi', 450, 215, 175, 40, 'Dabigatran', 'Directe orale trombineremmer. Antidotum: idarucizumab.'),
                ('biva', 450, 268, 175, 40, 'Bivalirudine', 'Directe trombineremmer, intraveneus (bv. bij een PCI).'),
                ('vka', 15, 250, 175, 56, 'VKA (coumarines)', 'Remmen de vitamine K-afhankelijke aanmaak van II, VII, IX en X (en proteïne C/S). Antidotum: vitamine K (+ protrombinecomplex).'),
            ], arrows=[('tf', 'xa', '->'), ('ix', 'xa', '->'), ('xa', 'iia', '->'), ('iia', 'fib', '->'),
                       ('xaban', 'xa', '-|'), ('fonda', 'xa', '-|'), ('hep', 'xa', '-|'), ('hep', 'iia', '-|'),
                       ('dabi', 'iia', '-|'), ('biva', 'iia', '-|'), ('vka', 'iia', '-|')]),
        ],
    ),

    # ================================================================== HC 5
    'HC5': dict(
        thema='T2', titel='Introductie hematologische maligniteiten', docent='dr. Margot Jak, internist-hematoloog', bron='HC 5',
        kern='Hematologische maligniteiten volgen de stamboom: stamcelziekten (acute leukemie, MDS, MPN) en lymfatische maligniteiten (Hodgkin, NHL inclusief CLL, myeloom en Waldenström). '
             'Elke maligniteit is een opeenstapeling van mutaties (klonale evolutie). De diagnose rust op morfologie, flowcytometrie, cytogenetica en moleculaire diagnostiek.',
        kapstok=[
            ('Hiërarchie', ['LT-HSC → ST-HSC → voorlopers (CMP, CLP, GMP, MEP) → rijpe cellen.',
                            'Stamcelmaligniteiten (AL, MDS, MPN) versus lymfatische maligniteiten (Hodgkin, NHL incl. CLL, MM, Waldenström).']),
            ('Genetica', ['Meerdere hits, meerdere klonen en cumulatie in de tijd: klonale evolutie (ook bij een recidief).',
                          'Pathways: groeifactorreceptoren, signaaltransductie, celcyclus, transcriptiefactoren, apoptose, epigenetica, RNA-splicing, cohesine → doelgerichte therapie.']),
            ('Diagnostiek', ['Telling + morfologie (bloed; beenmerg via cristabiopt, -aspiraat of sternumaspiraat).',
                             'Flowcytometrie: >10 parameters per cel, 10⁵-10⁶ cellen; een aberrant fenotype maakt MRD-meting mogelijk.',
                             'Cytogenetica: delende cellen nodig; t(9;22), t(15;17).',
                             'Moleculair: PCR, FISH, NGS, WES/WGS.']),
            ('Stamcelziekten', ['AL: uitrijpingsstop, ≥20% blasten, verdringing (anemie, neutropenie, trombopenie).',
                                'MDS: dysplasie + apoptose → cytopenie, <20% blasten; ±30% wordt AML.',
                                'MPN: te veel aanmaak met normale uitrijping (JAK2, CALR, MPL, BCR-ABL).']),
            ('MPN', ['PV: JAK2 bij 96%.',
                     'ET: JAK2, CALR of MPL.',
                     'MF: fibrose en extramedullaire hematopoëse.',
                     'CML: BCR-ABL; genetisch instabiel → blastencrise.']),
            ('Lymfatisch', ['Rearrangement van de receptor in het beenmerg; selectie en somatische hypermutatie in de klier.',
                            'Transformatie via anti-apoptose (t(14;18): BCL2), proliferatie (MYC, NFκB), virussen (EBV, HHV-8) en chronische antigeenstimulatie (H. pylori, Chlamydia psittaci).',
                            'Hodgkin: RS-cel + cytokines → B-symptomen. NHL: van indolent tot agressief. CLL: een indolent NHL in het bloed.',
                            'Plasmacel: M-proteïne (3% van de 70-plussers), myeloom (osteolyse → hypercalciëmie, fracturen), amyloïdose.']),
            ('Therapie', ['Immuunontsnapping (Treg, PD-L1) → antistoffen (rituximab, daratumumab), immunotoxine (brentuximab), checkpointremmers, CAR-T, bispecifieke antistoffen.',
                          'Stamceltransplantatie: autoloog (hoge-dosis chemo + rescue) versus allogeen (nieuw immuunsysteem: graft-versus-leukemie én GVHD).']),
        ],
        valkuilen=['De grens tussen AL en MDS ligt bij 20% blasten.',
                   'CLL is eigenlijk een lymfoom (indolent NHL) dat zich in het bloed laat zien.',
                   'Autoloog geeft geen GvL-effect; allogeen wel, maar ook GVHD.'],
        vragen=[
            ('Wat is het kernverschil tussen acute leukemie, MDS en MPN?',
             'AL: een uitrijpingsstop · MDS: dysplastische uitrijping met apoptose · MPN: te veel aanmaak met normale uitrijping',
             ['AL: te veel aanmaak · MDS: een uitrijpingsstop · MPN: dysplasie',
              'Alle drie zijn lymfatisch; ze verschillen alleen in het aantal blasten',
              'AL: normale uitrijping · MDS: te veel aanmaak · MPN: een uitrijpingsstop'],
             'Dat bepaalt het bloedbeeld: blasten en cytopenie (AL), cytopenie met dysplasie (MDS), te veel rijpe cellen (MPN).'),
            ('Vanaf hoeveel blasten in het beenmerg spreek je van acute leukemie?', '≥20%', ['≥5%', '≥10%', '≥50%'],
             'Onder de 20% met dysplasie spreek je van MDS (met blastenexces). Bepaalde genetische afwijkingen definiëren AML ook bij <20%.'),
            ('Hoe leidt de translocatie t(14;18) tot een lymfoom?',
             'BCL2 komt onder de IgH-promotor: de cel maakt te veel van het anti-apoptotische eiwit en gaat niet meer dood',
             ['MYC wordt geactiveerd, waardoor de cel sneller deelt', 'Er ontstaat een BCR-ABL-fusiekinase', 'PD-L1 wordt geamplificeerd'],
             'Klassiek bij het folliculair lymfoom. MYC hoort bij t(8;14) (Burkitt), BCR-ABL bij t(9;22) (CML).'),
            ('Waarom heb je voor klassieke karyotypering delende cellen nodig?', 'Chromosomen zijn alleen zichtbaar in de metafase van de celdeling',
             ['Flowcytometrie werkt alleen op delende cellen', 'Niet-delende cellen bevatten geen DNA', 'Alleen delende cellen hebben translocaties'],
             'FISH en moleculaire technieken werken ook op niet-delende cellen.'),
            ('Wat is het belangrijkste verschil tussen een autologe en een allogene stamceltransplantatie?',
             'Allogeen geeft een nieuw immuunsysteem met een graft-versus-leukemie-effect (en risico op GVHD); autoloog is alleen een rescue na hoge-dosis chemotherapie',
             ['Autoloog geeft meer GVHD dan allogeen', 'Bij allogeen worden de eigen ingevroren stamcellen teruggegeven', 'Bij autoloog worden donor-T-cellen gegeven'],
             'Donor-T-cellen ruimen de (maligne) hematopoëse van de patiënt op, maar kunnen ook normale weefsels aanvallen (huid, darm, lever).'),
        ],
        cel=('💥', 'Blast', 'Bij acute leukemie is ≥20% van de beenmergcellen een blast. Een Auerstaaf bewijst dat de blast myeloïd is.'),
        kaarten=[
            ('In welke subtypen werd MDS ingedeeld (WHO 2016)?',
             'MDS met ringsideroblasten, met single-lineage dysplasie, met multilineage dysplasie, met blastenexces, en MDS met een geïsoleerde del(5q).', False),
            ('In welke pathways treden mutaties op bij hematologische maligniteiten?',
             'I groeifactorreceptoren · II signaaltransductie · III celcyclusregulatoren · IV transcriptiefactoren · V celdood/apoptose · VI epigenetische regulatie en chromatineremodellering · VII RNA-splicingfactoren · VIII cohesinecomplex.\nKennis hiervan geeft een betere classificatie en prognose, en doelgerichte therapie.', False),
            ('Wat is de definitie van acute leukemie, en wat zijn de gevolgen van de verdringing?',
             '≥20% blasten in het beenmerg (proliferatie met een uitrijpingsstop).\nVerdringing van de normale hematopoëse (mede door een veranderd micromilieu) geeft anemie, neutropenie (infecties) en trombocytopenie (bloedingen).', True),
            ('Hoe deel je acute leukemie in op basis van morfologie en flowcytometrie?',
             'Lymfatisch (ALL: B-ALL of T-ALL), myeloïd (AML) of ongedifferentieerd (AUL: geen differentiatiemarkers).\nDaarnaast een indeling op basis van mutaties (WHO-risicoclassificatie).', False),
            ('Wat is multiparameterflowcytometrie, en waarvoor gebruik je een aberrant fenotype?',
             'Per cel worden tegelijk meer dan 10 eigenschappen gemeten (eiwitten op de membraan en intracellulair), voor 100.000 tot 1.000.000 cellen.\nLeukemiecellen hebben vaak een afwijkende combinatie van markers (bv. myeloïd + lymfatisch). Met die "vingerafdruk" spoor je minimale restziekte (MRD) op.', True),
            ('Waarom heb je voor klassieke cytogenetica delende cellen nodig?',
             'Chromosomen worden pas zichtbaar (en te banderen) in de metafase van de celdeling; daarom wordt beenmerg eerst gekweekt.\nFISH en moleculaire technieken werken ook op niet-delende cellen.', False),
            ('Wat is het paradoxale beenmergbeeld bij MDS?',
             'Het beenmerg is meestal juist celrijk (hypercellulair), maar door dysplasie en verhoogde apoptose komen er weinig cellen in het bloed: ineffectieve hematopoëse → cytopenie(ën).\nMyeloblasten <20%; circa 30% gaat over in AML.', True),
            ('Wat is het gemeenschappelijke mechanisme van de myeloproliferatieve neoplasmata?',
             'Mutaties in een cytokinereceptor (MPL, de G-CSF-receptor) of in een signaalroute (JAK2, STAT5, BCR-ABL) zetten de groei permanent aan: verhoogde aanmaak met normale uitrijping en functie.', True),
            ('Waarom worden PV, ET en MF pas sinds kort maligniteiten genoemd?',
             'Pas na de ontdekking van JAK2 (2005) en later CALR en MPL bleek het om klonale stamcelziekten te gaan; de oude term was myeloproliferatieve ziekte (MPD). Klinisch verlopen ze vaak relatief "benigne".\nCML werd al eerder herkend aan het Philadelphiachromosoom: BCR-ABL-positieve versus -negatieve MPN.', False),
            ('Welke zeldzame MPN- en overlapvormen bestaan er?',
             'Chronische eosinofiele leukemie, mastocytose, en MDS/MPN-overlap zoals chronische myelomonocytaire leukemie (CMML).', False),
            ('Waarom kan CML overgaan in een blastencrise?',
             'BCR-ABL geeft naast een groeivoordeel ook een grote genetische instabiliteit. Extra mutaties stapelen zich op, en de ziekte kan overgaan in een lymfatische of myeloïde blastencrise (acute leukemie).', False),
            ('Waar in de normale lymfocytenontwikkeling ontstaan B- en T-cellymfomen?',
             'In het beenmerg vindt de gene rearrangement van de B- en T-celreceptor plaats; fouten daarbij kunnen tot transformatie leiden.\nIn lymfeklier, milt en thymus volgen selectie en somatische hypermutatie. Cellen zonder hoog-affiene receptor gaan normaal in apoptose; ontsnappen daaraan geeft een lymfoom.', False),
            ('Hoe leidt de translocatie t(14;18) tot een lymfoom?',
             'BCL2 komt onder de promotor van de zware immunoglobulineketen (IgH). De B-cel maakt continu het anti-apoptotische BCL-2 en gaat niet meer dood.\nKlassiek bij het folliculair lymfoom.', True),
            ('Welke vier mechanismen dragen bij aan de transformatie van een B- of T-cel?',
             '1) Remming van apoptose (bv. t(14;18): BCL2)\n2) Activatie van proliferatieroutes (MYC, NFκB)\n3) Virussen (EBV, HHV-8)\n4) Chronische antigene stimulatie (Helicobacter pylori, Chlamydia psittaci)', True),
            ('Waarom heeft een patiënt met Hodgkin vaak B-symptomen?',
             'De Reed-Sternbergcel is omgeven door een groot reactief infiltraat, en er worden veel cytokines geproduceerd. Die geven koorts, nachtzweten en gewichtsverlies.', False),
            ('Waarom heet CLL een leukemie, terwijl het eigenlijk een lymfoom is?',
             'CLL is een indolent non-Hodgkinlymfoom (rijpe B-cellen met een gestoorde apoptose), maar de rijpe lymfocyten hopen zich op in het bloed. Vandaar de naam leukemie.', True),
            ('Hoe vaak vind je een M-proteïne bij ouderen?',
             'Bij circa 3% van de 70-plussers, 6% van de 80-plussers en 14% van de 90-plussers (meestal MGUS of een smouldering myeloom).', False),
            ('Hoe veroorzaakt multipel myeloom botafbraak?',
             'Myeloomcellen remmen de osteoblasten en stimuleren de osteoclasten: osteolytische haarden, met hypercalciëmie en (pathologische) fracturen.', True),
            ('Hoe ontsnappen maligniteiten aan het afweersysteem?',
             'Door tolerantie te induceren (regulatoire T-cellen) of door checkpointliganden op te reguleren, zoals PD-L1 bij Hodgkin en bij plasmacelziekten.\nCheckpointremmers (anti-PD-1, anti-PD-L1) heffen die rem op.', False),
            ('Wat is een immunotoxine? Geef een voorbeeld.',
             'Een monoklonaal antilichaam gekoppeld aan een toxine (antilichaam-medicijnconjugaat), bijvoorbeeld brentuximab vedotin (anti-CD30) bij Hodgkin.\nVoorbeelden zonder toxine: rituximab (anti-CD20), daratumumab (anti-CD38).', False),
        ],
        casus=[
            ('Man, 45 jaar, 30 dagen na een allogene stamceltransplantatie voor AML: een uitgebreid exantheem, waterdunne diarree en een stijgend bilirubine.',
             'Acute graft-versus-hostziekte', 'Donor-T-cellen herkennen de huid, de darm en de lever van de ontvanger als lichaamsvreemd. Hetzelfde mechanisme geeft het gewenste graft-versus-leukemie-effect.'),
        ],
        tabellen=[
            dict(id='almdsmpn', titel='Stamcelmaligniteiten vergeleken (HC 5)', kolommen=['Wat gaat er mis', 'Beenmerg', 'Bloed'], rijen=[
                ('Acute leukemie', ['Proliferatie met uitrijpingsstop', '≥20% blasten, normale hematopoëse verdrongen', 'Blasten + cytopenieën']),
                ('MDS', ['Dysplastische, ineffectieve uitrijping + apoptose', 'Meestal celrijk, dysplasie, <20% blasten', 'Cytopenie(ën) met dysplastische cellen']),
                ('MPN', ['Te veel aanmaak, normale uitrijping', 'Celrijk (bij myelofibrose: fibrose)', 'Te veel erytrocyten, plaatjes en/of leukocyten']),
            ]),
        ],
        schemas=[],
    ),
}

# Verzamelkaarten voor de colleges waarvan de slides nog niet zijn verwerkt (de campagne toont ze in het album).
CELLEN_OVERIG = {
    'HC6': ('🧬', 'Philadelphiachromosoom', 'Het eerste chromosoom dat aan een kanker werd gekoppeld (1960). De t(9;22) maakt het BCR-ABL-kinase, het doelwit van imatinib.'),
    'HC7': ('🦉', 'Reed-Sternbergcel', 'Met zijn twee kernen en dikke nucleoli kijkt hij je aan als een uil. Toch is hij maar een klein deel van de tumor.'),
    'HC8': ('🍳', 'Plasmacel', 'Een excentrische kern met een "radwiel"-chromatine en een lichte hof ernaast. Eén kloon kan grammen M-proteïne per liter maken.'),
    'HC9': ('🪡', 'Auerstaaf', 'Een naaldvormige samenklontering van azurofiele granula. Zie je hem, dan is de blast myeloïd.'),
    'HC10': ('🌌', 'Sterrenhemel', 'Het "starry sky"-beeld van Burkitt: lichte macrofagen die apoptotische cellen opruimen tussen donkere, snel delende tumorcellen.'),
    'HC11': ('🧸', 'Homer Wright-rozet', 'Een kransje tumorcellen rond een kern van neurofibrillen: typisch voor neuroblastoom.'),
    'HC12': ('🎒', 'AYA-kompas', 'Jongvolwassenen met kanker vallen tussen kinder- en volwassenenzorg: fertiliteit, school en werk vragen om eigen zorg.'),
    'HC13': ('🧭', 'G8-kompas', 'De G8 is een korte screener: een score ≤14 betekent dat een uitgebreid geriatrisch assessment zinvol is.'),
    'HCAI': ('🤖', 'Neuraal netwerk', 'Een AI-model is zo goed als de data waarop het is getraind. Een bias in de data wordt een bias in het advies.'),
    'HC14': ('🚬', 'Leukoplakie', 'Een witte plek die je niet kunt wegvegen. Erytroplakie (rood) is zeldzamer, maar veel vaker maligne.'),
    'HC15': ('☢️', 'Lineaire versneller', 'Radiotherapie in fracties geeft gezond weefsel tijd om te herstellen tussen de bestralingen door.'),
    'HC16': ('🐚', 'Keratineparel', 'Een rond nestje verhoornde cellen: het kenmerk van een goed gedifferentieerd plaveiselcelcarcinoom.'),
    'HC17': ('🦋', 'Psammomalichaampje', 'Een gelaagd kalkbolletje: typisch voor het papillair schildkliercarcinoom (en de schildklier is een vlinder).'),
    'HC18': ('👁️', 'Leukocorie', 'Een witte pupilreflex op een flitsfoto kan het eerste teken van een retinoblastoom zijn.'),
    'HC19': ('🎤', 'Stemband', 'Glottische tumoren geven al vroeg heesheid. Daardoor worden ze vroeg ontdekt, en ze metastaseren weinig.'),
    'PH1': ('🏛️', 'Lalonde', 'Vier determinanten van gezondheid: biologie, leefstijl, omgeving en de gezondheidszorg.'),
    'PH2': ('🔍', 'Screeningstest', 'Overdiagnose en lead time bias kunnen screening beter laten lijken dan hij is.'),
    'PH3': ('⚖️', 'Zorgwetten', 'Zvw, Wlz, Wmo en Jeugdwet: wie betaalt welke zorg?'),
    'PH4': ('💶', 'Naturapolis', 'De verzekeraar koopt de zorg in. Ga je naar een niet-gecontracteerde zorgverlener, dan betaal je vaak een deel zelf.'),
    'PH5': ('🩺', 'Huisarts', 'Een huisarts ziet gemiddeld maar enkele nieuwe kankerpatiënten per jaar, tussen duizenden onschuldige klachten.'),
    'PH6': ('🌍', 'Healthy migrant', 'Migranten zijn bij aankomst vaak gezonder dan gemiddeld; dat voordeel verdwijnt in de loop van de jaren.'),
    'PH7': ('🏭', 'Bedrijfsarts', 'De bedrijfsarts adviseert over belasting en belastbaarheid; de verzekeringsarts beoordeelt later de arbeidsongeschiktheid.'),
    'PH8': ('📑', 'Poortwachter', 'De Wet verbetering poortwachter: twee jaar re-integratie, pas daarna volgt de WIA-keuring.'),
    'HC28': ('🦽', 'ICF-model', 'Functies, activiteiten en participatie, met persoonlijke en externe factoren eromheen.'),
    'HC29': ('🫂', 'Lastmeter', 'Een thermometer van 0-10 voor distress. Vanaf 5 is een gesprek over extra hulp zinvol.'),
    'HC30': ('🕯️', 'Palliatieve fase', 'Palliatieve zorg begint niet pas in de stervensfase, maar zodra genezing niet meer mogelijk is.'),
    'HC31': ('🪜', 'Pijnladder', 'Bij pijn bij kanker: geef morfine op tijd, op de klok, en altijd met een laxans.'),
}
