"""Inhoud voor de speelse uitbreiding van het GZC III-deck.

CASUS      : 'Wie ben ik?'-kaarten (vignet -> diagnose + waarom). Ook bron voor de quiz.
SCHEMAS    : zelfgetekende schema's; per verborgen vak één kaart (schema-occlusie).
TABELLEN   : vergelijkingstabellen; per cel één kaart.
EZELSBRUG  : kaartnummer (#n uit werk/deck.txt) -> geheugensteun die op de achterkant komt.
QUIZ_EXTRA : losse meerkeuzevragen in tentamenstijl (eigen formulering).

Thema's: T1 benigne hemato, T2 maligne hemato, T3 kind/AYA/geriatrie, T4 hoofd-hals/schildklier/oog,
B1 public health, B2 revalidatie/psychosociaal, B3 pijn/palliatief.
"""

# ------------------------------------------------------------------ 1. wie ben ik?
# (thema, groep, vignet, diagnose, waarom)
CASUS = [
    # --- anemie
    ('T1', 'anemie', 'Man, 65 jaar, moe en kortademig bij traplopen. Hb 4,6 mmol/l, MCV 68 fl, MCHC laag, reticulocyten laag, ferritine sterk verlaagd.',
     'IJzergebreksanemie', 'Microcytair + hypochroom + laag ferritine. Bij een man van 65: gastro-intestinaal bloedverlies (coloncarcinoom!) tot het tegendeel bewezen is → gastro- én coloscopie.'),
    ('T1', 'anemie', 'Vrouw, 58 jaar, met actieve reumatoïde artritis. Hb 6,8 mmol/l, MCV 84 fl, ferritine 450 µg/l, transferrine laag, transferrinesaturatie laag.',
     'Anemie bij chronische ziekte', 'Inflammatie (IL-6) → hepcidine ↑ → ijzer opgesloten in macrofagen. Ferritine (positief acutefase-eiwit) hoog, transferrine (negatief acutefase-eiwit) laag.'),
    ('T1', 'anemie', 'Vrouw, 25 jaar, van Italiaanse afkomst, klachtenvrij. Hb 6,9 mmol/l, MCV 62 fl, erytrocyten 6,1 × 10¹²/l, ferritine normaal, HbA2 4,2%.',
     'Bèta-thalassemie minor', 'Sterk verlaagd MCV bij een hóóg erytrocytenaantal en normaal ferritine; HbA2 >3% bevestigt. Geen ijzer geven!'),
    ('T1', 'anemie', 'Vrouw, 62 jaar, met vitiligo, tintelende voeten en een gladde rode tong. Hb 5,9 mmol/l, MCV 118 fl, hypergesegmenteerde neutrofielen, antistoffen tegen intrinsic factor.',
     'Pernicieuze anemie (vitamine B12-deficiëntie)', 'Auto-immuun atrofische gastritis → geen intrinsic factor → geen B12-opname in het ileum. Megaloblastair + neurologie. Levenslang hydroxocobalamine; nooit alleen foliumzuur geven.'),
    ('T1', 'anemie', 'Jongen, 12 jaar, wisselende geelzucht, vergrote milt en galstenen. Reticulocyten verhoogd, MCHC verhoogd, sferocyten in de uitstrijk, DAT negatief. Vader heeft hetzelfde.',
     'Hereditaire sferocytose', 'Membraandefect → kogelcellen → extravasculaire hemolyse in de milt. Verhoogd MCHC is een zeldzaam en dus typisch kenmerk. Splenectomie helpt.'),
    ('T1', 'anemie', 'Man, 30 jaar, mediterrane afkomst, krijgt een dag na een maaltijd met tuinbonen donkere urine en geelzucht. Uitstrijk: bite cells en Heinz-lichaampjes.',
     'G6PD-deficiëntie', 'Te weinig gereduceerd glutathion → oxidatieve stress (tuinbonen, sulfonamiden, primaquine, infectie) → intravasculaire hemolyse.'),
    ('T1', 'anemie', 'Vrouw, 70 jaar, bekend met CLL, snel toenemend moe. Hb 5,5 mmol/l, reticulocyten hoog, LDH hoog, haptoglobine onmeetbaar, directe antiglobulinetest (Coombs) positief.',
     'Auto-immuun hemolytische anemie (warm type)', 'Hemolyseparameters + positieve DAT. CLL is een klassieke onderliggende oorzaak. Behandeling: prednison.'),
    ('T1', 'anemie', 'Man, 22 jaar, moe, bloedend tandvlees en infecties. Pancytopenie met laag reticulocytengetal. Beenmergbiopt: leeg en vervet, geen infiltratie of fibrose.',
     'Aplastische anemie', 'Hypocellulair merg zonder infiltratie. Meestal auto-immuun. Behandeling: ATG + ciclosporine of allogene stamceltransplantatie.'),
    ('T1', 'anemie', 'Man, 50 jaar, moe, pijnlijke handgewrichten en verhoogde leverenzymen. Transferrinesaturatie 78%, ferritine 1500 µg/l.',
     'Hereditaire hemochromatose (HFE C282Y)', 'Trias van Brissot: moeheid, gewrichtsklachten, verhoogde leverenzymen. Te weinig hepcidine → ongeremde ijzeropname. Behandeling: aderlaten.'),
    ('T1', 'anemie', 'Jongen, 8 jaar, Surinaamse afkomst, heeft bij koorts hevige pijn in armen en benen. Hb 5,5 mmol/l, MCV normaal, reticulocyten hoog, afwijkende band op Hb-elektroforese.',
     'Sikkelcelziekte', 'Kwalitatieve hemoglobinopathie (HbS): hemolyse + vaso-occlusieve pijncrise. MCV normaal, in tegenstelling tot thalassemie.'),
    ('T1', 'anemie', 'Man, 83 jaar, moe. Hb 6,2 mmol/l, MCV 112 fl, weinig reticulocyten, vitamine B12 en foliumzuur normaal. Uitstrijk: pseudo-Pelger-cellen.',
     'Myelodysplastisch syndroom (MDS)', 'Macrocytaire anemie bij een oudere met normale vitamines en dysplasie. Hypercellulair merg met ineffectieve hematopoëse; risico op AML.'),
    # --- stolling
    ('T1', 'stolling', 'Man, 24 jaar, van jongs af aan neusbloedingen en snel blauwe plekken. Na een kiesextractie direct 40 minuten nabloeden. Moeder had een nabloeding na de bevalling. Plaatjes, PT en aPTT normaal.',
     'Ziekte van Von Willebrand', 'Primaire hemostase (slijmvliezen, direct nabloeden), beide geslachten, autosomaal dominant. Normale PT/aPTT sluiten VWD niet uit → VWF-antigeen en -activiteit.'),
    ('T1', 'stolling', 'Jongen, 3 jaar, krijgt na een val een dikke, warme knie en later een grote spierbloeding in de kuit. aPTT verlengd, PT normaal, factor VIII <1%.',
     'Ernstige hemofilie A', 'Secundaire hemostase (gewrichten, spieren, uitgesteld nabloeden), X-gebonden, alleen jongens. Profylactisch factor VIII of emicizumab.'),
    ('T1', 'stolling', 'Vrouw, 30 jaar, sinds een week petechiën op de benen en bloedend tandvlees. Trombocyten 8 × 10⁹/l, overig bloedbeeld en stolling normaal, geen splenomegalie.',
     'Immuun-trombocytopenie (ITP)', 'Geïsoleerde trombocytopenie bij een verder gezonde patiënt: diagnose per exclusionem. Behandelen bij bloeding of zeer laag getal (prednison, IVIG).'),
    ('T1', 'stolling', 'Vrouw, 35 jaar, verward en koortsig. Trombocyten 12 × 10⁹/l, Hb laag met fragmentocyten, LDH sterk verhoogd, creatinine verhoogd. ADAMTS13-activiteit <5%.',
     'Trombotische trombocytopenische purpura (TTP)', 'Trombopenie + micro-angiopathische hemolyse + orgaanischemie door ongeknipte VWF-multimeren. Spoed: plasmaferese.'),
    ('T1', 'stolling', 'Man, 40 jaar, bloedt uit infuusplekken en tandvlees. Trombocyten laag, PT en aPTT verlengd, fibrinogeen laag, D-dimeer sterk verhoogd. Beenmerg: promyelocyten vol Auerse staven.',
     'Acute promyelocytenleukemie met DIS', 'APL t(15;17) veroorzaakt DIS: verbruik van stollingsfactoren en plaatjes. Direct ATRA starten — nu de best behandelbare AML.'),
    # --- myeloïd
    ('T2', 'myeloid', 'Man, 50 jaar, moe en een vol gevoel in de buik. Milt 10 cm onder de ribbenboog. Leukocyten 180 × 10⁹/l met alle granulocytaire rijpingsstadia en veel basofielen.',
     'Chronische myeloïde leukemie (CML)', 'Proliferatie mét uitrijping + basofilie + forse splenomegalie. BCR-ABL1 door t(9;22). Behandeling: TKI (imatinib).'),
    ('T2', 'myeloid', 'Man, 60 jaar, rood gelaat, hoofdpijn en jeuk na het douchen. Hb 11,5 mmol/l, hematocriet 0,56, EPO verlaagd, JAK2 V617F positief.',
     'Polycythaemia vera', 'Erytrocytose met láág EPO (autonoom) en JAK2. Aderlaten tot Ht <0,45, laagdosis aspirine, zo nodig hydroxycarbamide.'),
    ('T2', 'myeloid', 'Vrouw, 52 jaar, brandende pijnaanvallen in voeten en handen. Trombocyten 900 × 10⁹/l, overige lijnen normaal, CALR-mutatie aangetoond.',
     'Essentiële trombocytose', 'Geïsoleerde klonale trombocytose met erythromelalgie. Laagdosis aspirine; hydroxycarbamide bij hoog risico. Beste prognose van de MPN\'s.'),
    ('T2', 'myeloid', 'Vrouw, 68 jaar, vermagerd met nachtzweten. Enorme milt. Anemie met traandruppelcellen en een leuko-erytroblastair bloedbeeld. Beenmergaspiratie lukt niet (dry tap).',
     'Myelofibrose', 'Fibrose → extramedullaire hematopoëse in de milt. JAK2/CALR/MPL. Ruxolitinib voor klachten; allogene SCT is de enige curatieve optie.'),
    ('T2', 'myeloid', 'Man, 40 jaar, 2 weken ernstig moe, neusbloeding en petechiën. Hb 4,8, leukocyten 2,2, trombocyten 4. Uitstrijk 20% blasten, CD34+ CD33+. Translocatie t(8;21).',
     'Acute myeloïde leukemie (AML)', 'Beenmergverdringing (anemie, bloedingen, infecties) + ≥20% myeloïde blasten. t(8;21) is prognostisch gunstig.'),
    ('T2', 'myeloid', 'Man, 55 jaar, AML met leukocyten 180 × 10⁹/l, wordt benauwd, verward en ziet wazig.',
     'Leukostase', 'Te veel stugge blasten verstoppen de microcirculatie. Spoed: hydratie, snelle cytoreductie, zo nodig leukaferese; geen erytrocytentransfusie.'),
    # --- lymfoïd / plasmacel
    ('T2', 'lymfoid', 'Man, 68 jaar, moe, vergrote halsklieren. Lymfocyten 55 × 10⁹/l, monotone kleine lymfocyten met gumprechtse schollen. CD5+, CD19+, CD23+, zwak CD20.',
     'Chronische lymfatische leukemie (CLL)', 'Rijpe B-cel-lymfocytose ≥5 × 10⁹/l met typisch fenotype. Beenmergonderzoek niet nodig. Behandelen pas bij actieve ziekte.'),
    ('T2', 'lymfoid', 'Vrouw, 30 jaar, nachtzweten, koorts en 7 kg afgevallen. Pijnloze halsklieren die pijn doen na alcohol. Thorax: breed mediastinum. Biopt: grote cellen met uilenogen, CD30+ en CD15+.',
     'Klassiek Hodgkinlymfoom', 'Reed-Sternbergcellen in een reactieve achtergrond, CD30+/CD15+/CD20−. B-symptomen, bimodale leeftijdspiek. ABVD ± radiotherapie.'),
    ('T2', 'lymfoid', 'Man, 35 jaar, één langzaam groeiende halsklier, verder klachtenvrij. Biopt: popcorncellen die CD20+ zijn en CD30− en CD15−.',
     'Nodulair lymfocyten-predominant Hodgkinlymfoom (NLPHL)', 'CD20+ popcorncellen → rituximab werkt, anders dan bij klassiek Hodgkin. Indolent, meestal stadium I-II.'),
    ('T2', 'lymfoid', 'Man, 56 jaar, al een jaar pijnloze klieren in hals, oksels en liezen, voelt zich goed. Biopt: follikelvormige groei, CD10+ BCL2+, t(14;18).',
     'Folliculair lymfoom', 'Indolent kiemcentrumlymfoom, meestal stadium III-IV, niet te genezen. Wait-and-see zolang er geen klachten zijn. Risico op transformatie naar DLBCL.'),
    ('T2', 'lymfoid', 'Vrouw, 65 jaar, halszwelling die in enkele weken hard groeit, met koorts en nachtzweten. LDH sterk verhoogd. Biopt: diffuse vellen grote CD20+ B-cellen, Ki67 hoog.',
     'Diffuus grootcellig B-cellymfoom (DLBCL)', 'Agressief maar potentieel curatief met R-CHOP. Prognose volgens de IPI.'),
    ('T2', 'lymfoid', 'Jongen, 10 jaar, snel groeiende buikmassa bij de overgang van dunne naar dikke darm, met invaginatie. Biopt: starry sky-beeld, t(8;14).',
     'Burkitt-lymfoom (sporadische vorm)', 'MYC-translocatie, extreem snelle deling: behandeling binnen dagen, groot risico op tumorlysis, maar zeer chemogevoelig.'),
    ('T2', 'lymfoid', 'Vrouw, 60 jaar, al lang maagklachten, H. pylori positief. Maagbiopt: kleine lymfocyten die de klierbuizen infiltreren (lymfo-epitheliale laesies).',
     'MALT-lymfoom van de maag', 'Marginale-zonelymfoom door chronische antigene stimulatie. Eerste behandeling: H. pylori-eradicatie.'),
    ('T2', 'lymfoid', 'Man, 62 jaar, gegeneraliseerde lymfadenopathie, splenomegalie en beenmergbetrokkenheid. B-cellen CD5+, CD23−, cycline D1+, t(11;14).',
     'Mantelcellymfoom', 'CD5+ zoals CLL, maar CD23− en cycline D1+. Agressief beloop, vaker mannen.'),
    ('T2', 'lymfoid', 'Man, 50 jaar, enorme milt zonder vergrote klieren, pancytopenie. Beenmergaspiraat: dry tap. Cellen met haarachtige uitlopers, BRAF V600E.',
     'Hairy cell leukemie', 'Massale splenomegalie + pancytopenie + dry tap + BRAF. Indolent en zeer chemogevoelig.'),
    ('T2', 'lymfoid', 'Man, 55 jaar, al jaren eczeemplekken in het zwembroekgebied die tijdelijk op steroïdzalf reageren, nu verheven plaques. Biopt: CD4+ lymfocyten in de epidermis.',
     'Mycosis fungoides', 'Primair cutaan T-cellymfoom met epidermotropisme; indolent. Met circulerende tumorcellen en erythrodermie: Sézary-syndroom.'),
    ('T2', 'plasmacel', 'Man, 60 jaar, heftige rugpijn, verward en polyurie. Hb 6, creatinine 300, calcium 3,0. IgG-kappa M-proteïne 70 g/l, lytische laesies in schedel en wervels.',
     'Multipel myeloom', 'CRAB: hyperCalciëmie, Renale insufficiëntie, Anemie, Botlaesies. Rehydratie + bisfosfonaat, daarna inductie en autologe SCT.'),
    ('T2', 'plasmacel', 'Man, 72 jaar, klachtenvrij. Bij routinelab een IgG-kappa M-proteïne van 12 g/l. Beenmerg 5% plasmacellen, geen CRAB.',
     'MGUS', 'M-proteïne <30 g/l, <10% plasmacellen, géén orgaanschade. Progressie ~1% per jaar.'),
    ('T2', 'plasmacel', 'Man, 68 jaar, hoofdpijn, wazig zien en neusbloedingen. IgM-M-proteïne 40 g/l, lymfadenopathie en splenomegalie, geen botlaesies. MYD88-mutatie.',
     'Morbus Waldenström', 'IgM (pentameer) → hyperviscositeit. Klieren/milt, maar geen lytische laesies of hypercalciëmie. Plasmaferese bij hyperviscositeit.'),
    ('T2', 'plasmacel', 'Man, 65 jaar, nefrotisch syndroom, een vergrote tong en hartfalen. Vrije lambda-lichte ketens verhoogd. Vetbiopt: appelgroene dubbelbreking met Congorood.',
     'AL-amyloïdose', 'Neerslag van lichte-ketenfibrillen in nier, hart, zenuwen en tong. Behandeling gericht op de plasmacelkloon.'),
    # --- acuut/onco-emergencies (B3/T2)
    ('T2', 'acuut', 'Jongen, 10 jaar, met Burkitt-lymfoom, een dag na start van chemotherapie: kalium 6,8, fosfaat hoog, calcium laag, urinezuur hoog, nauwelijks urineproductie.',
     'Tumorlysissyndroom', 'Kalium, fosfaat en urinezuur omhoog, calcium omlaag, nierfalen door neerslag. Preventie: ruime hydratie + allopurinol/rasburicase.'),
    ('T2', 'acuut', 'Vrouw, 45 jaar, 10 dagen na een AML-kuur: temperatuur 38,6 °C, neutrofielen 0,1 × 10⁹/l, verder geen focus.',
     'Febriele neutropenie', 'Spoedgeval: kweken afnemen en binnen een uur breedspectrumantibiotica, niet wachten op uitslagen.'),
    ('B3', 'acuut', 'Vrouw, 55 jaar, gemetastaseerd mammacarcinoom. Sinds dagen toenemende rugpijn, erger bij liggen, gordelvormige uitstraling en nu zwakke benen.',
     'Dreigende dwarslaesie (myelumcompressie)', 'Spoed-MRI van de hele wervelkolom, direct dexamethason, daarna radiotherapie of decompressie. Wie nog loopt, blijft lopen.'),
    ('B3', 'acuut', 'Man, 68 jaar, plaveiselcelcarcinoom van de long, is dorstig, obstipatie, suf en verward. Calcium 3,4 mmol/l, PTH laag.',
     'Hypercalciëmie door maligniteit (PTHrP)', 'Humorale hypercalciëmie: tumor maakt PTHrP, eigen PTH onderdrukt. Rehydratie + bisfosfonaat.'),
    ('B3', 'acuut', 'Patiënt in de terminale fase is stil en teruggetrokken, reageert wisselend over de dag, weet niet waar hij is en plukt af en toe aan het laken.',
     'Delier (hypoactief/gemengd)', 'Acuut, fluctuerend, gestoorde aandacht. De hypoactieve vorm wordt vaak voor depressie aangezien. Oorzaak zoeken; haloperidol.'),
    # --- kind
    ('T3', 'kind', 'Meisje, 4 jaar, wil niet meer staan, beenpijn, bleek, koorts, blauwe plekken, hepatosplenomegalie. 75% blasten; CD19+, CD10+, TdT+; t(12;21).',
     'Acute lymfatische leukemie (common B-ALL)', 'Meest voorkomende kinderkanker, piek 2-5 jaar. t(12;21) is gunstig. Overleving ~90%.'),
    ('T3', 'kind', 'Jongen, 3 jaar, hangerig met koorts en een grote buikmassa links die de middellijn overschrijdt. Urine: VMA en HVA verhoogd. MIBG-scan: tumor bijnier + botmetastasen.',
     'Neuroblastoom', 'Neurale lijst/bijniermerg, catecholaminen in urine, MIBG-opname. N-MYC-amplificatie is ongunstig.'),
    ('T3', 'kind', 'Meisje, 3 jaar, moeder voelt bij het wassen een gladde, pijnloze buikmassa die de middellijn niet overschrijdt. Bloeddruk verhoogd, microscopische hematurie.',
     'Nefroblastoom (Wilms-tumor)', 'Behandeling op beeldvorming zonder biopt vooraf (SIOP): preoperatieve chemo → nefrectomie. Genezing ~90%.'),
    ('T3', 'kind', 'Baby van 14 maanden: op foto\'s licht één pupil wit op in plaats van rood, en het kindje kijkt scheel.',
     'Retinoblastoom', 'Leukocorie + strabismus. RB1-mutatie; bilateraal = altijd erfelijk. Kalk in de tumor is vrijwel pathognomonisch.'),
    ('T3', 'kind', 'Jongen, 15 jaar, al 2 maanden \'s nachts pijn boven de knie met zwelling. Röntgen: zonnestraaltjes en een Codman-driehoek in de metafyse.',
     'Osteosarcoom', 'Metafyse rond de knie tijdens de groeispurt. Neoadjuvante chemo + ruime resectie; niet stralingsgevoelig.'),
    ('T3', 'kind', 'Meisje, 12 jaar, pijn en zwelling van het bekken met koorts en een verhoogde BSE. Röntgen: uienschil-periostreactie. Translocatie t(11;22).',
     'Ewing-sarcoom', 'Diafyse en platte beenderen, EWSR1-FLI1. Wél stralingsgevoelig: chemo + chirurgie en/of radiotherapie.'),
    ('T3', 'kind', 'Jongen, 7 jaar: binnen enkele dagen een blauw, gezwollen ooglid met een naar voren en omlaag staand oog.',
     'Orbitaal rhabdomyosarcoom', 'Meest voorkomende maligne orbitatumor bij kinderen. Groeit in dagen → dezelfde dag biopteren en behandelen. Overleving ~90%.'),
    # --- hoofd-hals
    ('T4', 'hoofdhals', 'Vrouw, 62 jaar, rookt en drinkt, pijn in de linkeronderkaak die uitstraalt naar het oor. Prothese past niet meer, 8 kg afgevallen. Exofytische afwijking op de processus alveolaris.',
     'Plaveiselcelcarcinoom van de mondholte', 'Roken + alcohol, referred otalgie (n. V), slecht passende prothese. Primair chirurgie met halsklierbehandeling.'),
    ('T4', 'hoofdhals', 'Man, 65 jaar, rookt 40 jaar, sinds 5 weken hees. Geen slikklachten, geen halsklieren.',
     'Glottisch larynxcarcinoom', 'Heesheid is vroeg symptoom; ware stembanden hebben nauwelijks lymfedrainage → laat klieren. Verwijzen bij heesheid >3 weken.'),
    ('T4', 'hoofdhals', 'Vrouw, 76 jaar, globusgevoel, pijn in het linkeroor, veranderde stem. Wel een vergrote klier hoog in de hals.',
     'Supraglottisch larynxcarcinoom', 'Laat klachten, maar rijke lymfedrainage → vaak al kliermetastasen. Referred otalgie via de n. vagus.'),
    ('T4', 'hoofdhals', 'Man, 45 jaar, afkomstig uit Zuid-China: eenzijdig verminderd gehoor door vocht achter het trommelvlies, een halsklier en sinds kort dubbelzien.',
     'Nasofarynxcarcinoom', 'EBV-geassocieerd. Eenzijdige otitis media met effusie bij een volwassene = nasofarynx inspecteren. Dubbelzien: schedelbasisdoorgroei. Behandeling: (chemo)radiotherapie.'),
    ('T4', 'hoofdhals', 'Man, 48 jaar, nooit gerookt, cystische zwelling in de hals. Kleine tumor in de tonsil. Immunohistochemie: p16 sterk positief.',
     'HPV-positief orofarynxcarcinoom', 'Jongere niet-rokers, cystische kliermetastase, kleine primaire tumor. Betere prognose (~80% vijfjaarsoverleving).'),
    ('T4', 'hoofdhals', 'Vrouw, 40 jaar, al jaren een langzaam groeiende, pijnloze, vaste zwelling vóór het oor. Gezicht beweegt normaal.',
     'Pleiomorf adenoom van de parotis', 'Meest voorkomende speekselkliertumor. Onvolledig kapsel met pseudopodieën → geen enucleatie maar oppervlakkige parotidectomie.'),
    ('T4', 'hoofdhals', 'Man, 68 jaar, zware roker, zachte zwellingen in beide parotiden.',
     'Warthin-tumor', 'Tweede benigne speekselkliertumor: oudere rokers, vaak bilateraal, alleen parotis. Vrijwel nooit maligne.'),
    ('T4', 'hoofdhals', 'Man, 55 jaar, snel groeiende pijnlijke parotiszwelling. De mondhoek aan die kant hangt.',
     'Maligne speekselkliertumor', 'Facialisparese bij een parotiszwelling = maligne tot het tegendeel bewezen is. Ook alarm: pijn, snelle groei, fixatie, halsklieren.'),
    # --- schildklier
    ('T4', 'schildklier', 'Vrouw, 35 jaar, sinds 3 weken een vast knobbeltje links in de schildklier en vergrote halsklieren. TSH normaal. Punctie: cellen met ingekeepte kernen.',
     'Papillair schildkliercarcinoom', 'Meest voorkomend (~80%), lymfogene verspreiding, BRAF V600E. Thyreoïdectomie + I-131-ablatie; prognose zeer goed.'),
    ('T4', 'schildklier', 'Man, 40 jaar, schildkliernodus en halsklier; veel dunne ontlasting. Tweelingbroer heeft recent medullaire schildklierkanker gekregen.',
     'Medullair schildkliercarcinoom bij MEN2A', 'C-cellen → calcitonine (diarree). RET-kiembaanmutatie. Eerst feochromocytoom uitsluiten, dan thyreoïdectomie. Geen I-131.'),
    ('T4', 'schildklier', 'Man, 72 jaar: schildklier in 3 weken hard en onregelmatig gegroeid, vast aan de omgeving, met benauwdheid, slikklachten en gewichtsverlies.',
     'Anaplastisch schildkliercarcinoom', 'Oudere, explosieve groei, altijd stadium IV, geen jodiumopname. Zeer slechte prognose (maanden).'),
    ('T4', 'schildklier', 'Vrouw, 45 jaar, hartkloppingen en gewichtsverlies. TSH onderdrukt. Scintigrafie: één nodus die alles opneemt, rest van de schildklier onderdrukt.',
     'Toxisch folliculair adenoom (hete nodus)', 'Activerende TSH-receptormutatie → autonome productie. Behandeling met radioactief jodium of operatie.'),
    # --- oog
    ('T4', 'oog', 'Man, 62 jaar, ziet lichtflitsen. Fundoscopie: gepigmenteerde, paddenstoelvormige tumor van de choroidea met netvliesloslating.',
     'Uveamelanoom (choroïdeamelanoom)', 'Meest voorkomende primaire intraoculaire tumor bij volwassenen. Metastaseert hematogeen naar de lever. Brachytherapie of enucleatie.'),
    ('T4', 'oog', 'Vrouw, 70 jaar, op het onderooglid een kratertje met parelmoerachtige opgeworpen rand, teleangiëctasieën en verlies van wimpers.',
     'Basaalcelcarcinoom van het ooglid', 'Meest voorkomende ooglidtumor, onderooglid/mediale ooghoek. Lokaal destructief, zaait vrijwel nooit uit. Excisie met margecontrole.'),
    ('T4', 'oog', 'Vrouw, 72 jaar, steeds terugkomend "chalazion" op het bovenooglid met een geelrode kleur.',
     'Talgkliercarcinoom van het ooglid', 'Verraderlijk: lijkt op een recidiverend chalazion, maar is agressief en zaait snel uit. Altijd biopteren.'),
    ('T4', 'oog', 'Man, 68 jaar, zalmkleurige, pijnloze zwelling onder de conjunctiva.',
     'Non-Hodgkinlymfoom van de orbita (salmon patch)', 'Altijd biopteren en verwijzen naar de hematoloog voor stadiëring; lokaal radiotherapie.'),
    # --- pijn
    ('B3', 'pijn', 'Man, 58 jaar, na resectie van de n. ischiadicus: brandende, tintelende pijn in het been met schietende scheuten. Aanraking van de huid doet pijn.',
     'Neuropathische pijn', 'Beschadiging van het zenuwstelsel: brandend, schietend, allodynie. Behandeling: amitriptyline/duloxetine of gabapentine/pregabaline.'),
    ('B3', 'pijn', 'Vrouw, 64 jaar, pancreascarcinoom: doffe, zeurende, slecht te lokaliseren pijn in de bovenbuik met uitstraling naar de rug, onvoldoende reactie op opioïden.',
     'Viscerale nociceptieve pijn → plexus coeliacusblokkade', 'Viscerale bovenbuikpijn reageert goed op een neurolytische blokkade van de plexus coeliacus/splanchnicus.'),
]

# ------------------------------------------------------------------ 2. schema's
# box: (id, x, y, w, h, tekst (\n = nieuwe regel), uitleg of None als het vak niet verborgen wordt)
# pijl: (van, naar, soort) soort: '->' activeert, '-|' remt, '--' lijn
SCHEMAS = [
    dict(id='stolling', thema='T1', titel='Stollingscascade', w=640, h=430, boxes=[
        ('tf', 20, 30, 200, 48, 'Tissue factor + VIIa', 'Extrinsieke route: start van de stolling in vivo. Gemeten met de PT/INR.'),
        ('xii', 470, 20, 150, 38, 'XII', 'Contactactivatie. In vivo niet nodig: een tekort geeft géén bloedingen, wel een verlengde aPTT.'),
        ('xi', 470, 80, 150, 38, 'XI', 'Intrinsieke route; gemeten met de aPTT.'),
        ('ix', 440, 140, 180, 44, 'IX + VIIIa', 'Tenasecomplex: factor IX (tekort = hemofilie B) met cofactor VIII (tekort = hemofilie A).'),
        ('x', 200, 210, 230, 48, 'X → Xa (+ Va)', 'Gemeenschappelijke route: Xa met cofactor Va vormt het protrombinasecomplex. Aangrijpingspunt van rivaroxaban, apixaban en (via antitrombine) heparine.'),
        ('ii', 180, 285, 270, 48, 'Protrombine (II) → trombine', 'Trombine zet fibrinogeen om en versterkt zichzelf via Va en VIIIa. Dabigatran remt trombine direct.'),
        ('fib', 180, 360, 270, 44, 'Fibrinogeen → fibrine', 'Eindproduct: het fibrinenetwerk dat de plaatjesplug stabiliseert.'),
        ('xiii', 470, 360, 150, 44, 'XIIIa', 'Crosslinkt fibrine. Tekort geeft bloedingen bij een normale PT én aPTT.'),
        ('pt', 20, 100, 150, 30, 'PT meet dit', None),
        ('aptt', 470, 196, 150, 30, 'aPTT meet dit', None),
        ('vka', 20, 250, 150, 70, 'VKA remt\nII, VII, IX, X\n(„1972”)', None),
    ], arrows=[('tf', 'x', '->'), ('xii', 'xi', '->'), ('xi', 'ix', '->'), ('ix', 'x', '->'), ('x', 'ii', '->'), ('ii', 'fib', '->'), ('xiii', 'fib', '->')]),

    dict(id='primhemostase', thema='T1', titel='Primaire hemostase: van vaatwand tot plaatjesplug', w=640, h=320, boxes=[
        ('coll', 20, 270, 600, 36, 'Beschadigde vaatwand: subendotheliaal collageen', None),
        ('vwf', 30, 200, 190, 44, 'Von Willebrand-factor', 'Brug tussen collageen en de trombocyt. Tekort = ziekte van Von Willebrand (meest voorkomende erfelijke bloedingsziekte).'),
        ('gpib', 50, 125, 150, 40, 'GpIb', 'Adhesiereceptor op de trombocyt die VWF bindt. Defect = Bernard-Soulier (reuzenplaatjes).'),
        ('plt1', 30, 40, 190, 48, 'Trombocyt', None),
        ('act', 250, 30, 200, 56, 'ADP + tromboxaan A2\n(positieve feedback)', 'Activatie: ADP via P2Y12 (geremd door clopidogrel) en TxA2 via COX-1 (geremd door acetylsalicylzuur).'),
        ('gp2b', 250, 140, 200, 56, 'GpIIb/IIIa +\nfibrinogeen', 'Aggregatie: fibrinogeen koppelt twee plaatjes via GpIIb/IIIa. Defect = ziekte van Glanzmann; geremd door abciximab.'),
        ('plt2', 480, 40, 140, 48, 'Trombocyt', None),
    ], arrows=[('vwf', 'gpib', '--'), ('gpib', 'plt1', '--'), ('plt1', 'act', '->'), ('act', 'plt2', '->'), ('plt1', 'gp2b', '--'), ('gp2b', 'plt2', '--')]),

    dict(id='epo', thema='T1', titel='Regelkring van de erytropoëse', w=640, h=330, boxes=[
        ('nier', 30, 30, 200, 56, 'Nier: zuurstofsensor\n(HIF)', 'Bij hypoxie wordt HIF niet afgebroken en zet het de EPO-productie aan (Von Hippel-Lindau breekt HIF normaal af).'),
        ('epo', 280, 38, 80, 40, 'EPO', 'Groeifactor uit de nier die erytroïde voorlopers (CFU-E) in het beenmerg stimuleert.'),
        ('bm', 410, 30, 200, 56, 'Beenmerg: erytropoëse\n(ijzer, B12, folaat)', 'Hier worden erytrocyten gemaakt; reticulocyten tonen hoe goed het merg reageert.'),
        ('ery', 410, 140, 200, 48, 'Hb en erytrocyten ↑', None),
        ('o2', 410, 250, 200, 56, 'O2-transport\n(longen + hart)', 'Longen (opname) en hart (pompfunctie) bepalen samen met het Hb het zuurstofaanbod.'),
        ('weef', 30, 250, 200, 56, 'Weefsel-O2 ↑\n→ minder EPO', 'Negatieve terugkoppeling: het zuurstofaanbod is hersteld, dus de nier maakt minder EPO.'),
    ], arrows=[('nier', 'epo', '->'), ('epo', 'bm', '->'), ('bm', 'ery', '->'), ('ery', 'o2', '->'), ('o2', 'weef', '->'), ('weef', 'nier', '-|')]),

    dict(id='hepcidine', thema='T1', titel='Hepcidine: de „insuline voor ijzer”', w=640, h=330, boxes=[
        ('up', 20, 20, 280, 56, '↑ door inflammatie (IL-6)\nen ijzeroverschot', 'Daarom stijgt hepcidine bij ontsteking → ijzer opgesloten → anemie bij chronische ziekte.'),
        ('down', 340, 20, 280, 56, '↓ door erythroferrone (EPO),\nijzergebrek en hypoxie', 'Veel (ineffectieve) erytropoëse onderdrukt hepcidine → ijzerstapeling bij thalassemie, ook zonder transfusies.'),
        ('lever', 220, 125, 200, 48, 'Lever maakt hepcidine', None),
        ('darm', 20, 240, 280, 56, 'Ferroportine in de enterocyt', 'Hepcidine blokkeert ferroportine in het duodenum → minder ijzeropname uit de voeding.'),
        ('mf', 340, 240, 280, 56, 'Ferroportine in de macrofaag', 'Hepcidine blokkeert ferroportine in macrofagen → ijzer uit oude erytrocyten blijft opgesloten.'),
    ], arrows=[('up', 'lever', '->'), ('down', 'lever', '-|'), ('lever', 'darm', '-|'), ('lever', 'mf', '-|')]),

    dict(id='stamcel', thema='T2', titel='Waar ontstaan de hematologische maligniteiten?', w=640, h=420, boxes=[
        ('hsc', 200, 15, 240, 44, 'Hematopoëtische stamcel', None),
        ('mye', 20, 100, 260, 60, 'Myeloïde voorloper:\nAML · MDS · MPN (CML, PV, ET, MF)', 'Stamcelmaligniteiten uit de myeloïde lijn.'),
        ('lym', 360, 100, 260, 44, 'Lymfoïde voorloper: ALL', 'Onrijpe lymfoblasten (TdT+): B-ALL of T-ALL.'),
        ('bn', 330, 185, 290, 44, 'Naïeve B-cel: CLL, mantelcel', 'CD5+ B-cellymfomen: CLL (CD23+) en mantelcellymfoom (cycline D1+, CD23−).'),
        ('kc', 330, 245, 290, 44, 'Kiemcentrum: FL, DLBCL, Burkitt, Hodgkin', 'Kiemcentrum-B-cellen: folliculair lymfoom, DLBCL, Burkitt én (klassiek) Hodgkin.'),
        ('mz', 330, 305, 290, 44, 'Marginale zone: MALT, hairy cell', 'Geheugen-/marginale-zone-B-cellen: MALT-lymfoom en hairy cell leukemie.'),
        ('pc', 330, 365, 290, 44, 'Plasmacel: MGUS, myeloom, (Waldenström)', 'Plasmacelziekten met een M-proteïne; Waldenström zit tussen lymfoom en myeloom in (lymfoplasmacytair, IgM).'),
        ('t', 20, 245, 260, 60, 'T-cel: T-ALL, perifeer T-cellymfoom,\nmycosis fungoides', 'T-cellymfomen; mycosis fungoides is een CD4+ cutaan T-cellymfoom.'),
    ], arrows=[('hsc', 'mye', '->'), ('hsc', 'lym', '->'), ('lym', 'bn', '->'), ('bn', 'kc', '->'), ('kc', 'mz', '->'), ('mz', 'pc', '->'), ('lym', 't', '->')]),

    dict(id='anemie', thema='T1', titel='Anemie: eerst het MCV', w=640, h=360, boxes=[
        ('mcv', 220, 15, 200, 44, 'Anemie → MCV?', None),
        ('micro', 10, 110, 200, 90, 'MCV < 80: microcytair\nIJzergebrek, thalassemie,\n(ACD), sideroblastair', 'Altijd een hemoglobinesynthesestoornis: heem (ijzer, lood, sideroblastair) of globine (thalassemie). Eerst ferritine bepalen.'),
        ('normo', 220, 110, 200, 60, 'MCV 80-100:\nnormocytair → reticulocyten?', None),
        ('macro', 430, 110, 200, 90, 'MCV > 100: macrocytair\nB12/folaat, alcohol, lever,\nhypothyreoïdie, MDS', 'Megaloblastair (B12/folaat) of niet-megaloblastair (alcohol, lever, hypothyreoïdie, MDS, medicatie).'),
        ('laag', 120, 250, 190, 80, 'Reticulocyten laag:\naanmaak (ACD, nier,\nbeenmerg)', 'Het merg reageert niet: anemie bij chronische ziekte, nierinsufficiëntie (EPO-tekort) of beenmergprobleem.'),
        ('hoog', 330, 250, 190, 80, 'Reticulocyten hoog:\nhemolyse of\nbloedverlies', 'Het merg reageert goed: het probleem zit in de periferie. Bij hemolyse: LDH ↑, haptoglobine ↓, indirect bilirubine ↑, DAT.'),
    ], arrows=[('mcv', 'micro', '->'), ('mcv', 'normo', '->'), ('mcv', 'macro', '->'), ('normo', 'laag', '->'), ('normo', 'hoog', '->')]),

    dict(id='myeloom', thema='T2', titel='Het plasmacelspectrum', w=640, h=200, boxes=[
        ('mgus', 10, 40, 140, 110, 'MGUS\nM-prot <30 g/l\n<10% plasmacel\ngeen CRAB', 'Voorstadium zonder orgaanschade; progressie ~1% per jaar.'),
        ('smo', 170, 40, 140, 110, 'Smouldering\nM-prot ≥30 of\n≥10% plasmacel\ngeen CRAB', 'Asymptomatisch myeloom: meer ziekte dan MGUS, maar nog geen orgaanschade → nog niet behandelen.'),
        ('mm', 330, 40, 140, 110, 'Multipel\nmyeloom\nmét CRAB', 'Orgaanschade (hyperCalciëmie, Renaal, Anemie, Botlaesies) = behandelindicatie.'),
        ('pcl', 490, 40, 140, 110, 'Plasmacel-\nleukemie', 'Eindstadium: de cellen hebben het beenmergmilieu niet meer nodig en circuleren in het bloed.'),
    ], arrows=[('mgus', 'smo', '->'), ('smo', 'mm', '->'), ('mm', 'pcl', '->')]),

    dict(id='halslevels', thema='T4', titel='Lymfeklierniveaus in de hals (schematisch, zijaanzicht; gezicht links)', w=640, h=380, boxes=[
        ('kaak', 20, 15, 330, 30, 'onderkaak', None),
        ('l1', 20, 60, 150, 70, 'I', 'Level I: submentaal en submandibulair. Drainage van lip, mondbodem, voorste tong en wang.'),
        ('l2', 190, 60, 150, 70, 'II', 'Level II: hoog jugulair. Drainage van orofarynx, supraglottis, parotis en nasofarynx — vaak de eerste halsklier.'),
        ('l3', 190, 145, 150, 70, 'III', 'Level III: midjugulair. Drainage van hypofarynx, larynx en orofarynx.'),
        ('l4', 190, 230, 150, 70, 'IV', 'Level IV: laag jugulair. Drainage van hypofarynx, subglottis, schildklier, oesofagus (en infraclaviculaire tumoren).'),
        ('l5', 360, 60, 150, 240, 'V', 'Level V: achterste halsdriehoek (achter de m. sternocleidomastoideus). Drainage van nasofarynx en huid van het achterhoofd.'),
        ('l6', 20, 230, 150, 70, 'VI', 'Level VI: centraal compartiment, vóór de trachea. Drainage van schildklier, subglottis en cervicale oesofagus.'),
        ('scm', 530, 60, 90, 240, 'm. sterno-\ncleido-\nmastoideus\n(achter II-IV)', None),
        ('clav', 20, 320, 490, 30, 'sleutelbeen', None),
    ], arrows=[]),

    dict(id='pijnladder', thema='B3', titel='WHO-pijnladder (nociceptieve pijn bij kanker)', w=640, h=330, boxes=[
        ('s1', 20, 250, 190, 60, 'Stap 1: paracetamol\n± NSAID', 'Paracetamol 4 × 1000 mg; NSAID met maagbescherming. Pas omhoog als dit adequaat gedoseerd onvoldoende werkt.'),
        ('s2', 160, 175, 190, 60, 'Stap 2: zwak opioïd\n(tramadol)', 'Bij kanker vaak overgeslagen: meteen door naar een sterk opioïd in lage dosis.'),
        ('s3', 300, 100, 190, 60, 'Stap 3: sterk opioïd\n(morfine, oxycodon)', 'Langwerkend basispreparaat + kortwerkende rescue (~1/6 dagdosis) + altijd een laxans.'),
        ('s4', 440, 25, 180, 60, 'Stap 4: parenteraal /\ninvasief', 'Subcutaan/intraveneus, of invasieve technieken (intrathecaal, plexusblokkade, chordotomie).'),
        ('pr', 20, 25, 380, 56, 'By mouth · by the clock ·\nby the ladder · for the individual', None),
    ], arrows=[]),

    dict(id='braken', thema='B3', titel='Braakcentrum: vier ingangen', w=640, h=330, boxes=[
        ('bc', 220, 135, 200, 56, 'Braakcentrum\n(hersenstam)', None),
        ('gi', 20, 20, 260, 60, 'Maag-darm via n. vagus\n(5-HT3)', 'Chemotherapie, obstructie, obstipatie, gastroparese. Ondansetron (5-HT3), metoclopramide als prokineticum.'),
        ('ctz', 360, 20, 260, 60, 'Chemoreceptor trigger zone\n(D2)', 'Opioïden, chemo, uremie, hypercalciëmie. Haloperidol of metoclopramide (D2-antagonisten).'),
        ('vest', 20, 250, 260, 60, 'Evenwichtsorgaan\n(H1, acetylcholine)', 'Bewegingsgebonden misselijkheid. Cinnarizine/cyclizine (H1) of scopolamine.'),
        ('cortex', 360, 250, 260, 60, 'Cortex: angst,\nanticipatie, hersendruk', 'Anticipatoire misselijkheid: benzodiazepine. Verhoogde intracraniële druk: dexamethason.'),
    ], arrows=[('gi', 'bc', '->'), ('ctz', 'bc', '->'), ('vest', 'bc', '->'), ('cortex', 'bc', '->')]),

    dict(id='icf', thema='B2', titel='ICF-model (voorbeeld: patiënt na laryngectomie)', w=640, h=330, boxes=[
        ('ziekte', 170, 15, 300, 44, 'Aandoening: larynxcarcinoom', None),
        ('func', 10, 115, 190, 70, 'Functies &\nanatomie', 'Stoornis in een lichaamsfunctie of -structuur: geen stembanden, geen natuurlijke stem.'),
        ('act', 225, 115, 190, 70, 'Activiteiten', 'Wat iemand (niet) kan doen: bellen, zich verstaanbaar maken.'),
        ('part', 440, 115, 190, 70, 'Participatie', 'Deelname aan het maatschappelijk leven: werk als docent, vereniging, sociale contacten.'),
        ('ext', 60, 245, 240, 60, 'Externe factoren', 'Omgeving: stemprothese, begripvolle werkgever, logopedie, partner.'),
        ('pers', 340, 245, 240, 60, 'Persoonlijke factoren', 'Leeftijd, coping, motivatie, opleiding — belemmerend of bevorderend.'),
    ], arrows=[('ziekte', 'act', '--'), ('func', 'act', '--'), ('act', 'part', '--'), ('ext', 'act', '--'), ('pers', 'act', '--')]),

    dict(id='lalonde', thema='B1', titel='Model van Lalonde: determinanten van gezondheid', w=640, h=300, boxes=[
        ('gez', 230, 120, 180, 50, 'Gezondheid', None),
        ('bio', 20, 20, 260, 60, 'Biologie / erfelijkheid', 'Leeftijd, geslacht, genetische aanleg (bijv. BRCA, Lynch).'),
        ('leef', 360, 20, 260, 60, 'Leefstijl', 'Roken, alcohol, voeding, beweging — het grootste beïnvloedbare deel van de kankerlast.'),
        ('omg', 20, 220, 260, 60, 'Omgeving (fysiek en sociaal)', 'Luchtvervuiling, asbest, uv, woon- en werkomstandigheden, sociaal-economische status.'),
        ('zorg', 360, 220, 260, 60, 'Gezondheidszorg', 'Toegankelijkheid en kwaliteit van preventie, screening en behandeling.'),
    ], arrows=[('bio', 'gez', '->'), ('leef', 'gez', '->'), ('omg', 'gez', '->'), ('zorg', 'gez', '->')]),

    dict(id='screening', thema='B1', titel='Testeigenschappen (2×2-tabel)', w=640, h=330, boxes=[
        ('h1', 170, 15, 200, 36, 'Ziek', None),
        ('h2', 390, 15, 200, 36, 'Niet ziek', None),
        ('r1', 10, 65, 140, 60, 'Test +', None),
        ('r2', 10, 140, 140, 60, 'Test −', None),
        ('a', 170, 65, 200, 60, 'a = terecht positief', None),
        ('b', 390, 65, 200, 60, 'b = fout-positief', None),
        ('c', 170, 140, 200, 60, 'c = fout-negatief', None),
        ('d', 390, 140, 200, 60, 'd = terecht negatief', None),
        ('sens', 10, 225, 145, 80, 'Sensitiviteit\na / (a + c)', 'Kans op een positieve test bij zieken. Hoog = goed om uit te sluiten (SnNout). Onafhankelijk van prevalentie.'),
        ('spec', 165, 225, 145, 80, 'Specificiteit\nd / (b + d)', 'Kans op een negatieve test bij gezonden. Hoog = goed om aan te tonen (SpPin). Onafhankelijk van prevalentie.'),
        ('pvw', 320, 225, 145, 80, 'PVW\na / (a + b)', 'Kans dat een positieve test echt ziek is. Daalt sterk bij lage prevalentie (screening!).'),
        ('nvw', 475, 225, 145, 80, 'NVW\nd / (c + d)', 'Kans dat een negatieve test echt gezond is. Hangt ook af van de prevalentie.'),
    ], arrows=[]),

    dict(id='nodus', thema='T4', titel='Schildkliernodus: stappenplan', w=640, h=360, boxes=[
        ('start', 220, 15, 200, 44, 'Nodus → eerst TSH', None),
        ('laag', 20, 100, 260, 56, 'TSH laag →\nscintigrafie', 'Bij een onderdrukt TSH: kijken of de nodus zelf hormoon maakt.'),
        ('norm', 360, 100, 260, 56, 'TSH normaal/hoog →\necho + cytologische punctie', 'De meeste nodi. Punctie beoordeeld met de Bethesda-classificatie (6 categorieën).'),
        ('heet', 20, 200, 120, 60, 'Heet', 'Autonoom (toxisch) adenoom: zelden maligne → I-131 of operatie.'),
        ('koud', 160, 200, 120, 60, 'Koud', 'Neemt geen jodium op → verder met echo + punctie.'),
        ('uit', 360, 200, 260, 120, 'Benigne → vervolgen\nOnbepaald → diagnostische\nhemithyreoïdectomie\nMaligne → operatie', 'Beleid volgt de Bethesda-categorie van de punctie.'),
    ], arrows=[('start', 'laag', '->'), ('start', 'norm', '->'), ('laag', 'heet', '->'), ('laag', 'koud', '->'), ('norm', 'uit', '->')]),
]

# ------------------------------------------------------------------ 3. vergelijkingstabellen
# kolommen = ziekten; rijen = kenmerk; cellen kort houden
TABELLEN = [
    dict(id='mpn', thema='T2', titel='Myeloproliferatieve neoplasmata', kolommen=['CML', 'PV', 'ET', 'Myelofibrose'], rijen=[
        ('Mutatie', ['BCR-ABL1, t(9;22)', 'JAK2 V617F (~96%)', 'JAK2, CALR of MPL', 'JAK2, CALR of MPL']),
        ('Bloedbeeld', ['Leukocytose, alle rijpingsstadia + basofilie', 'Erytrocytose, EPO laag', 'Trombocyten >450', 'Leuko-erytroblastair, traandruppelcellen']),
        ('Typisch klinisch', ['Forse splenomegalie', 'Plethora, jeuk na douchen, trombose', 'Erythromelalgie, trombose én bloeding', 'Enorme milt, dry tap, B-klachten']),
        ('Behandeling', ['TKI (imatinib)', 'Aderlaten (Ht <0,45) + aspirine', 'Aspirine ± hydroxycarbamide', 'Ruxolitinib; allo-SCT curatief']),
    ]),
    dict(id='lymfoom', thema='T2', titel='Hodgkin vs. non-Hodgkin (blokboek tabel 1)', kolommen=['Klassiek Hodgkin', 'NLPHL', 'Non-Hodgkin'], rijen=[
        ('Markers', ['CD30+, CD15+, CD20−', 'CD20+, CD30−, CD15−', 'B-cel (CD20) of T-cel (CD3)']),
        ('Verspreiding', ['Voorspelbaar, klier naar klier', 'Gelokaliseerd, perifere klieren', 'Willekeurig, 1/3 extranodaal']),
        ('Leeftijd', ['Bimodaal: 20-30 en >55', 'Mannen 30-50', 'Stijgt met leeftijd']),
    ]),
    dict(id='acuut', thema='T2', titel='ALL vs. AML', kolommen=['ALL', 'AML'], rijen=[
        ('Wie', ['Vooral kinderen (piek 2-5 jaar)', 'Vooral ouderen (mediaan 65-70)']),
        ('Kenmerk', ['TdT+, CD19/CD10 (B) of CD3 (T)', 'Auerse staven, MPO+, CD33/CD117']),
        ('Extramedullair', ['CZS, testis, mediastinum (T-ALL)', 'Gingiva, huid, chloroom']),
        ('Prognose kind', ['~90% overleving', 'Slechter dan ALL (~70%)']),
    ]),
    dict(id='bloeding', thema='T1', titel='Erfelijke bloedingsziekten', kolommen=['Hemofilie A', 'Hemofilie B', 'Von Willebrand'], rijen=[
        ('Tekort', ['Factor VIII', 'Factor IX', 'Von Willebrand-factor (± FVIII)']),
        ('Overerving', ['X-gebonden recessief', 'X-gebonden recessief', 'Meestal autosomaal dominant']),
        ('Bloedingen', ['Gewrichten, spieren, uitgesteld', 'Gewrichten, spieren, uitgesteld', 'Slijmvliezen, direct nabloeden']),
        ('Behandeling', ['FVIII-concentraat, emicizumab; licht: DDAVP', 'FIX-concentraat (DDAVP werkt niet)', 'DDAVP (type 1), VWF-concentraat']),
    ]),
    dict(id='micro', thema='T1', titel='Microcytaire anemie onderscheiden', kolommen=['IJzergebrek', 'Chronische ziekte', 'Bèta-thal minor'], rijen=[
        ('Ferritine', ['Laag', 'Normaal tot hoog', 'Normaal']),
        ('Transferrine/TIBC', ['Hoog', 'Laag', 'Normaal']),
        ('Typisch', ['RDW hoog', 'Vaak normocytair', 'Erytrocyten hoog, HbA2 >3%']),
    ]),
    dict(id='schildklier', thema='T4', titel='Schildkliercarcinomen', kolommen=['Papillair', 'Folliculair', 'Medullair', 'Anaplastisch'], rijen=[
        ('Verspreiding', ['Lymfogeen (halsklieren)', 'Hematogeen (long, bot)', 'Lymfogeen + hematogeen', 'Lokaal invasief, snel']),
        ('Genetica / marker', ['BRAF V600E; Tg', 'RAS, PAX8-PPARG; Tg', 'RET; calcitonine + CEA', 'Vaak BRAF/TP53; geen Tg']),
        ('I-131 zinvol?', ['Ja', 'Ja', 'Nee (C-cellen)', 'Nee']),
    ]),
    dict(id='plasma', thema='T2', titel='M-proteïneziekten', kolommen=['MGUS', 'Multipel myeloom', 'Waldenström'], rijen=[
        ('M-proteïne', ['<30 g/l, meestal IgG', 'IgG of IgA (of lichte ketens)', 'IgM']),
        ('Beenmerg', ['<10% plasmacellen', '≥10% klonale plasmacellen', 'Lymfoplasmacytaire infiltratie']),
        ('Kliniek', ['Geen (géén CRAB)', 'CRAB: Ca, nier, anemie, bot', 'Hyperviscositeit, klieren, milt']),
    ]),
    dict(id='translocaties', thema='T2', titel='Translocaties die je moet kennen', kolommen=['Translocatie + gen'], rijen=[
        ('Burkitt-lymfoom', ['t(8;14) · MYC']),
        ('Folliculair lymfoom', ['t(14;18) · BCL2']),
        ('Mantelcellymfoom', ['t(11;14) · cycline D1']),
        ('CML', ['t(9;22) · BCR-ABL1']),
        ('Acute promyelocytenleukemie', ['t(15;17) · PML-RARA']),
        ('Ewing-sarcoom', ['t(11;22) · EWSR1-FLI1']),
        ('Kinder-ALL (gunstig)', ['t(12;21) · ETV6-RUNX1']),
        ('AML (gunstig)', ['t(8;21) · RUNX1-RUNX1T1']),
    ]),
    dict(id='pijn', thema='B3', titel='Soorten pijn', kolommen=['Somatisch', 'Visceraal', 'Neuropathisch'], rijen=[
        ('Karakter', ['Scherp, zeurend, goed te lokaliseren', 'Dof, krampend, slecht te lokaliseren', 'Brandend, schietend, allodynie']),
        ('Eerste keus', ['Paracetamol/NSAID → opioïd', 'Opioïd; plexusblokkade', 'Amitriptyline of pregabaline']),
    ]),
    dict(id='arts', thema='B1', titel='Bedrijfsarts vs. verzekeringsarts', kolommen=['Bedrijfsarts', 'Verzekeringsarts'], rijen=[
        ('Rol', ['Begeleidend: verzuim en re-integratie', 'Beoordelend: recht op uitkering']),
        ('Werkt voor/bij', ['Werkgever (arbodienst)', 'UWV (WIA, Ziektewet)']),
    ]),
    dict(id='bot', thema='T3', titel='Bottumoren bij kinderen', kolommen=['Osteosarcoom', 'Ewing-sarcoom'], rijen=[
        ('Lokalisatie', ['Metafyse, rond de knie', 'Diafyse, platte beenderen (bekken)']),
        ('Röntgen', ['Zonnestralen, Codman-driehoek', 'Uienschil-periostreactie']),
        ('Radiotherapie', ['Niet stralingsgevoelig', 'Wél stralingsgevoelig']),
    ]),
    dict(id='buik', thema='T3', titel='Buikmassa bij een peuter', kolommen=['Neuroblastoom', 'Nefroblastoom (Wilms)'], rijen=[
        ('Uitgangspunt', ['Neurale lijst (bijniermerg)', 'Nier']),
        ('Middellijn', ['Overschrijdt vaak de middellijn', 'Blijft aan één kant']),
        ('Diagnostiek', ['VMA/HVA in urine, MIBG, biopt', 'Echo/MRI, géén biopt vooraf (SIOP)']),
    ]),
    dict(id='zorgwet', thema='B1', titel='Zorgwetten', kolommen=['Zvw', 'Wlz', 'Wmo', 'Wpg', 'Jeugdwet'], rijen=[
        ('Wie voert uit', ['Zorgverzekeraar', 'Zorgkantoor (indicatie CIZ)', 'Gemeente', 'Gemeente / GGD', 'Gemeente']),
        ('Waarvoor', ['Curatieve basiszorg', '24-uurszorg, blijvend toezicht', 'Zelfredzaamheid, participatie', 'Collectieve preventie', 'Jeugdhulp en -GGZ']),
    ]),
    dict(id='larynx', thema='T4', titel='Larynxcarcinoom naar lokalisatie', kolommen=['Glottisch', 'Supraglottisch'], rijen=[
        ('Eerste klacht', ['Vroeg heesheid', 'Laat: globus, otalgie']),
        ('Kliermetastasen', ['Laat (arme lymfedrainage)', 'Vroeg (rijke drainage)']),
    ]),
]

# ------------------------------------------------------------------ 4. ezelsbruggen
EZELSBRUG = {
    97: 'CD5 + CD23 = CLL. CD5 zonder CD23 (maar mét cycline D1) = mantelcel.',
    112: '„Stones, bones, groans, thrones and psychiatric overtones”: nierstenen, botpijn, buikklachten/obstipatie, polyurie en verwardheid.',
    114: 'CRAB = Calcium, Renaal, Anemie, Bot.',
    210: 'MEN2A = 2 P\'s + M: Pheochromocytoom, Parathyreoïd, Medullair. MEN2B: M + P + marfanoïde habitus en mucosale neurinomen (geen hyperparathyreoïdie).',
    234: 'SnNout: hoge Sensitiviteit, Negatief → ziekte uitgesloten (rule out). SpPin: hoge Specificiteit, Positief → ziekte aangetoond (rule in).',
    235: 'Weinig zieken in de populatie → de meeste positieven zijn fout-positief. Screening = lage prevalentie = lage PVW.',
    307: '1972 → factor 10, 9, 7, 2 (plus proteïne C en S).',
    328: 'KNG: Koorts >38 °C, Nachtzweten, Gewichtsverlies >10% in 6 maanden.',
    329: '„3 omhoog, 1 omlaag”: kalium, fosfaat, urinezuur ↑ — calcium ↓.',
    542: 'Eerst B12, dan pas folaat: alleen foliumzuur geven maskeert de anemie, terwijl de zenuwschade doorgaat.',
    449: 'V-IX-X = mond, orofarynx, larynx/hypofarynx: de pijn komt „via de achterdeur” in het oor.',
    159: 'Neuroblastoom Neemt de middellijn; Wilms blijft Weg van de middellijn.',
    633: 'Bilateraal = altijd erfelijk (kiembaan RB1).',
    310: 'Virchow = SEH: Stase, Endotheelschade, Hypercoagulabiliteit.',
    405: '8,1 en 7,5: mannen hebben „meer” nodig (13 en 12 g/dl).',
    416: '„1-5”: <1% ernstig (spontane bloedingen), 1-5% matig, >5% mild.',
    436: 'JAK2 = het gaspedaal dat blijft hangen: EPO-, TPO- en GM-CSF-signaal staat continu aan.',
    125: '7 + 3: zeven dagen cytarabine, drie dagen antracycline.',
    77: 'Ann Arbor = tel de zijden van het diafragma: I één station, II één zijde, III beide zijden, IV buiten de klieren.',
    258: 'Revalidatie kijkt naar functioneren, niet naar de tumor: denk in ICF (functies → activiteiten → participatie).',
    506: 'Denk EINDIG: Eindigheid, geen toekomst, zinverlies, angst/wanhoop, eenzaamheid, onmacht, identiteitsverwarring.',
    520: '„By mouth, by the clock, by the ladder, for the individual.”',
    275: 'Opioïden: tolerantie voor misselijkheid en sufheid, NOOIT voor obstipatie → altijd een laxans.',
    319: 'Ferritine = brandweer bij ontsteking (↑); transferrine gaat met vakantie (↓).',
    583: 'Folliculair = 14;18 → BCL2 houdt de cel in leven (anti-apoptose).',
}

# ------------------------------------------------------------------ 6. quiz: losse tentamenvragen
# (thema, vraag, [juist, fout, fout, fout], uitleg)
QUIZ_EXTRA = [
    ('T2', 'Bij welk lymfoom kan rituximab (anti-CD20) effect hebben?', ['Nodulair lymfocyten-predominant Hodgkinlymfoom', 'Klassiek Hodgkinlymfoom', 'T-ALL', 'Acute myeloïde leukemie'], 'De popcorncellen van NLPHL zijn CD20+. Klassiek Hodgkin is CD20−, CD30+/CD15+.'),
    ('T2', 'Welk kenmerk past bij MGUS?', ['M-proteïne <30 g/l', '>10% plasmacellen in het beenmerg', 'Lytische botlaesies', 'B-symptomen'], 'MGUS: M-proteïne <30 g/l, <10% plasmacellen en géén CRAB.'),
    ('T2', 'Welke combinatie van M-proteïne en ziekte klopt?', ['Myeloom IgG/IgA — Waldenström IgM', 'Myeloom IgM — Waldenström IgA', 'Myeloom IgM — Waldenström IgG', 'Myeloom IgE — Waldenström IgG'], 'IgM is de pentameer van Waldenström (hyperviscositeit); myeloom is meestal IgG, dan IgA.'),
    ('T2', 'Welk non-Hodgkinlymfoom is in principe níet te genezen?', ['Folliculair lymfoom', 'Diffuus grootcellig B-cellymfoom', 'Burkitt-lymfoom', 'Hodgkinlymfoom'], 'Indolente (laaggradige) lymfomen zijn goed te behandelen maar niet te genezen; agressieve lymfomen zijn juist potentieel curabel.'),
    ('B1', 'Boven welke kans op een ernstige ziekte (bv. kanker) verwijst de huisarts volgens het college voor aanvullende diagnostiek?', ['3%', '1%', '10%', '20%'], 'Een voorafkans van circa 3% is de gebruikte drempel.'),
    ('B2', 'Wat is níet typerend voor een existentiële crisis?', ['Sterk verlangen naar de dood', 'Overweldigende emoties', 'Gevoel van onmacht', 'Het gevoel in een bodemloze put te vallen'], 'Kenmerken: eindigheid, wegvallen toekomst, zinverlies, angst en wanhoop, eenzaamheid, onmacht, identiteitsverwarring. Doodsverlangen hoort er niet bij.'),
    ('B1', 'Wat houdt de convergentiehypothese in?', ['Het kankerrisico van migranten verschuift in de tijd naar dat van de autochtone bevolking', 'Zeldzame kankers worden door globalisering vaker', 'Derde generatie migranten hebben hetzelfde risico als hun grootouders', 'Migranten zijn gezonder dan de bevolking van het gastland'], 'Door het overnemen van leefstijl en omgeving convergeert het risico. (Het laatste antwoord is het healthy migrant effect.)'),
    ('T4', 'Juist of onjuist: HPV-positieve orofarynxcarcinomen hebben een slechtere prognose.', ['Onjuist', 'Juist'], 'HPV-positief: ~80% vijfjaarsoverleving vs. ~50% bij HPV-negatief.'),
    ('T4', 'Juist of onjuist: lymfekliermetastasen komen vaker voor bij supraglottische dan bij glottische tumoren.', ['Juist', 'Onjuist'], 'De supraglottis heeft een rijke lymfedrainage, de ware stembanden nauwelijks.'),
    ('T4', 'Welk kenmerk past bij een plaveiselcelcarcinoom?', ['Desmosomen en keratine-expressie', 'Afwezigheid van verhoorning', 'Toename van melanocyten', 'CD20-positiviteit'], 'Plaveiselcelcarcinoom: verhoorning, intercellulaire bruggen (desmosomen), keratine.'),
    ('T2', 'Wat doet imatinib?', ['Het blokkeert de ATP-bindingsplaats van BCR-ABL', 'Het remt JAK2', 'Het stimuleert apoptose via CD20', 'Het corrigeert de translocatie t(9;22)'], 'Imatinib is een tyrosinekinaseremmer die de ATP-bindingsplaats van het BCR-ABL-kinase bezet.'),
    ('T2', 'Wat bepaalt vooral de behandelkeuze bij AML?', ['Het cytogenetische/moleculaire profiel van de blasten', 'Het blastenpercentage', 'De diepte van de cytopenieën', 'Het geslacht'], 'Genetica (ELN-risicogroep) bepaalt prognose en of allogene SCT nodig is.'),
    ('T2', 'Welk ziektebeeld kenmerkt zich door een effectieve hematopoëse (proliferatie mét uitrijping)?', ['CML', 'AML', 'MDS', 'Myelofibrose'], 'CML: proliferatiestoornis met vrijwel normale uitrijping. MDS juist ineffectief, AML uitrijpingsstop.'),
    ('T2', 'Hodgkin: pathologische klieren in hals, mediastinum en para-aortaal, plus de milt; lever en beenmerg normaal. Welk Ann Arbor-stadium?', ['IIIS', 'II', 'IIE', 'IV'], 'Beide zijden van het diafragma = III; milt (lymfoïd orgaan) = S, geen stadium IV.'),
    ('T1', 'Welke component is in vivo níet nodig voor een adequate stolling?', ['Factor XII', 'Tissue factor', 'Von Willebrand-factor', 'Trombocyten'], 'Factor XII-deficiëntie verlengt de aPTT maar geeft geen bloedingen.'),
    ('T1', 'Welke uitspraak over acetylsalicylzuur klopt?', ['Het verstoort de primaire hemostase door tromboxaanvorming te voorkomen', 'Het verstoort de secundaire hemostase via tromboxaan', 'Het blokkeert de P2Y12-receptor', 'Het remt vitamine K-epoxidereductase'], 'Irreversibele COX-1-remming → geen TxA2 → minder plaatjesactivatie.'),
    ('T1', 'Welke stap in de hemostase treedt als eerste op?', ['Binding van de trombocyt aan VWF via GpIb', 'Binding aan fibrinogeen via GpIIb/IIIa', 'Binding van trombine aan fibrinogeen', 'Release van dense granulae'], 'Eerst adhesie (VWF–GpIb), dan activatie (granulae), dan aggregatie (GpIIb/IIIa).'),
    ('T1', 'Een verlengde aPTT door heparinecontaminatie kenmerkt zich door:', ['Een verlengde aPTT én een verlengde trombinetijd', 'Een verlengde aPTT en een normale trombinetijd', 'Een normale aPTT en verlengde bloedingstijd', 'Alleen een verlengde PFA'], 'Heparine verlengt ook de TT; daarom check je bij een onverklaard lange aPTT eerst de TT.'),
    ('T1', 'Bij welke aandoening is het transferrine verhoogd?', ['IJzergebreksanemie', 'Anemie bij chronische ziekte', 'Thalassemie', 'Hemochromatose'], 'Bij ijzergebrek maakt de lever meer transferrine; bij ontsteking daalt het (negatief acutefase-eiwit).'),
    ('T1', 'Welk medicament grijpt níet aan op de primaire hemostase?', ['Acenocoumarol (Sintrom)', 'Abciximab', 'Acetylsalicylzuur', 'Clopidogrel'], 'VKA remmen vitamine K-afhankelijke stollingsfactoren: secundaire hemostase.'),
    ('T1', 'Welk eiwit speelt een rol bij het ontstaan van TTP?', ['ADAMTS13', 'Proteïne C', 'Antitrombine', 'Factor VIII'], 'Tekort aan ADAMTS13 → ultragrote VWF-multimeren → microtrombi.'),
    ('T1', 'Een neonaat krijgt vlak na de geboorte een hersenbloeding; PT en aPTT zijn normaal. Meest waarschijnlijke oorzaak?', ['Factor XIII-deficiëntie', 'Ernstige hemofilie A', 'Factor XI-deficiëntie', 'Factor X-deficiëntie'], 'Factor XIII wordt niet gemeten door PT/aPTT.'),
    ('T3', 'Wat is de volgorde van incidentie van maligniteiten bij kinderen?', ['Leukemie, dan hersentumoren', 'Hersentumoren, dan leukemie', 'Leukemie, dan retinoblastoom', 'Neuroblastoom, dan leukemie'], 'Leukemie is de meest voorkomende kinderkanker, hersentumoren zijn de grootste groep solide tumoren.'),
    ('T3', 'Waardoor wordt de prognose van ALL bij kinderen vooral bepaald?', ['Cytogenetica, therapierespons (MRD) en leeftijd', 'Cytogenetica, mediastinale verbreding en geslacht', 'Duur van de klachten en leukocytenaantal', 'Tumorlysis, leeftijd en trisomie 21'], 'MRD-respons is de sterkste factor, naast genetica en leeftijd (<1 en >10 jaar ongunstig).'),
    ('T3', 'Welke uitspraak over het retinoblastoom klopt?', ['Een bilateraal retinoblastoom berust altijd op een kiembaanmutatie', 'Een unilateraal retinoblastoom is nooit erfelijk', 'Het RB1-gen is een proto-oncogen', 'Het komt niet voor zonder kiembaanmutatie'], 'Bilateraal = altijd erfelijk; van de unilaterale is ~10% erfelijk. RB1 is een tumorsuppressorgen.'),
    ('T4', 'Otalgie bij een patiënt met een hoofd-halstumor duidt op:', ['Diepe doorgroei van de tumor (referred pain)', 'Otitis media', 'Betrokkenheid van de n. auricularis magnus', 'Betrokkenheid van de n. tympanicus'], 'Referred otalgie via V, IX of X is een alarmsymptoom voor diepe invasie.'),
    ('T4', 'Doorroken tijdens radiotherapie voor een hoofd-halstumor leidt NIET tot meer:', ['Afstandsmetastasen', 'Tweede tumoren', 'Lokale recidieven', 'Complicaties'], 'Roken verslechtert oxygenatie en genezing en geeft tweede tumoren, maar niet meer afstandsmetastasen.'),
    ('T4', 'Waarom een versneld bestralingsschema bij hoofd-halstumoren?', ['Om de kans op locoregionale controle te verhogen', 'Om de totale dosis te verhogen', 'Om late complicaties te verminderen', 'Om acute reacties te verminderen'], 'Korter schema = minder tijd voor tumorrepopulatie.'),
    ('T4', 'Dubbelzien bij een nasofarynxcarcinoom duidt op:', ['Doorgroei in de schedelbasis', 'Doorgroei in de n. opticus', 'Doorgroei in de sinus maxillaris', 'Meningitis carcinomatosa'], 'Schedelbasisdoorgroei geeft hersenzenuwuitval, vaak eerst de n. abducens.'),
    ('T4', 'De kans dat een zwelling in een kleine speekselklier maligne is, is ... dan in een grote speekselklier.', ['Groter', 'Kleiner', 'Gelijk', 'Niet te voorspellen'], 'Hoe kleiner de klier, hoe groter de kans op maligniteit.'),
    ('T4', 'Het recidiefrisico na verwijdering van een pleiomorf adenoom hangt vooral af van:', ['De operatietechniek (enucleatie vs. resectie met marge)', 'Het aantal mitosen', 'De tumorgrootte', 'Het type stroma'], 'Door het onvolledige kapsel met pseudopodieën recidiveert het na enucleatie.'),
    ('T4', 'Het RET-proto-oncogen speelt een rol bij:', ['Papillair en medullair schildkliercarcinoom', 'Folliculair en anaplastisch', 'Papillair en folliculair', 'Alleen anaplastisch'], 'RET/PTC-herschikkingen bij papillair, RET-mutaties bij medullair (MEN2).'),
    ('B3', 'Wat wordt verstaan onder de cognitieve dimensie van een symptoom?', ['De betekenis die aan het symptoom wordt toegekend', 'De subjectieve beleving', 'De emoties eromheen', 'Wat iemand met het symptoom doet'], 'Cognitief = betekenis („ik ga stikken”); sensorisch = beleving; affectief = emotie; gedragsmatig = doen.'),
    ('B3', 'U schrijft slow-release morfine voor. Wat schrijft u nog meer voor?', ['Kortwerkende morfine én een laxans', 'Alleen een laxans', 'Alleen kortwerkende morfine', 'Geen van beide'], 'Altijd rescue-medicatie (~1/6 dagdosis) én profylactisch een laxans.'),
    ('B3', 'Welke invasieve ingreep bij bovenbuikpijn door levermetastasen of pancreascarcinoom?', ['Plexus coeliacusblokkade', 'Chordotomie', 'Plexus hypogastricusblokkade', 'Geen, invasief helpt niet'], 'Viscerale bovenbuikpijn → plexus coeliacus/splanchnicus.'),
    ('B3', 'Meest effectieve symptomatische behandeling van dyspneu door uitgebreide longmetastasen?', ['Morfine', 'Zuurstof', 'Salmeterol', 'Dexamethason'], 'Morfine vermindert de sensatie van benauwdheid; zuurstof alleen bij hypoxemie.'),
    ('B3', 'Ascites bij gemetastaseerde maligniteit ontstaat meestal door:', ['Peritonitis carcinomatosa', 'Levermetastasen', 'Obstructie van lymfebanen', 'Trombose van de vv. hepaticae'], 'Maligne ascites komt meestal door peritoneale metastasen; diuretica helpen dan nauwelijks.'),
    ('B3', 'Welke neurotransmitter speelt géén rol bij misselijkheid en braken?', ['Noradrenaline', 'Dopamine', 'Serotonine', 'Histamine'], 'D2, 5-HT3, H1, muscarine en NK1 wel.'),
    ('B2', 'Welke uitspraak over psychosociale zorg is juist?', ['Een behandelend arts hoort bij elke kankerpatiënt te inventariseren of er behoefte is aan psychosociale ondersteuning', 'De Lastmeter is alleen voor patiënten bij wie al problemen zijn vastgesteld', 'Bij een lage Lastmeterscore heeft begeleiding geen zin', 'Iedere patiënt heeft professionele begeleiding nodig'], 'Signaleren bij iedereen; verwijzen op geleide van behoefte (Lastmeter ≥5 is een gespreksaanleiding).'),
    ('B2', 'Welk kenmerk hoort NIET bij het specifieke trauma van kanker?', ['Verminking', 'De dreiging komt van binnenuit', 'De onzekerheid duurt lang', 'Veel verliezen'], 'Specifiek voor kanker: dreiging van binnenuit, langdurige onzekerheid, veel verliezen.'),
    ('T1', 'Een icterische patiënt heeft een macrocytaire anemie (MCV 105) met een sterk verhoogd indirect bilirubine. Meest waarschijnlijk?', ['Hemolyse', 'Vitamine B12-tekort', 'Foliumzuurtekort', 'Alcoholische leverziekte'], 'Indirect bilirubine ↑ = hemolyse; de macrocytose komt door veel (grote) reticulocyten.'),
    ('T1', 'Welke uitspraak over sikkelcelziekte is ONJUIST?', ['Het MCV is altijd verlaagd, net als bij thalassemie', 'Heterozygoten hebben weinig of geen klachten', 'Er is reticulocytose door hemolyse', 'Foliumzuur hoort bij de behandeling'], 'Sikkelcelziekte is kwalitatief: MCV normaal.'),
]
